-- 移植：旧 pxr-access-control-manage-service の各エンティティ（src/repositories/postgres/*.ts）から組み立てた。
-- 旧実装は synchronize: false で、テーブルの DDL をリポジトリに持たないため、エンティティの定義から起こした。
-- 旧 MIT ライセンス（Copyright 2022 NEC Corporation）の表示は NOTICE を参照。
-- 旧 ormconfig の database は pxr_pod、schema は pxr_access_manage。DB の作成は含まない。
-- TypeORM の既定（nullable 指定なし = NOT NULL）に従う。nullable: true の列はない。
--
-- 注記（エンティティの定義と、DDL の対応）
-- - token_access_history.destination_user_id：エンティティに nullable の指定がないため NOT NULL。要確認。
-- - api_token、destination_api_url、destination_api_method、destination_user_id：エンティティは長さの指定がない varchar のため、長さなしで作った。
-- - created_history_id（token_access_history、caller_role）：エンティティは bigint に default: false と書く。PostgreSQL では bigint に false は入らないため、DEFAULT は付けなかった。
-- - token_generation_history.caller_api_url、caller_api_method：列の定義は bigint（TS の型は string）。列の型に合わせた。API の URL・メソッドを bigint にする理由は不明。要確認。

CREATE SCHEMA IF NOT EXISTS pxr_access_manage;

CREATE TABLE IF NOT EXISTS pxr_access_manage.token_access_history (
    id                              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_history_id              bigint NOT NULL,
    api_token                       varchar NOT NULL,
    destination_block_catalog_code  bigint NOT NULL,
    destination_api_url             varchar NOT NULL,
    destination_api_method          varchar NOT NULL,
    destination_user_id             varchar NOT NULL,
    expiration_at                   timestamp without time zone NOT NULL,
    parameter                       varchar NOT NULL,
    status                          smallint NOT NULL,
    is_disabled                     boolean NOT NULL DEFAULT false,
    created_by                      varchar(255) NOT NULL,
    created_at                      timestamp without time zone NOT NULL DEFAULT now(),
    updated_by                      varchar(255) NOT NULL,
    updated_at                      timestamp without time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pxr_access_manage.token_generation_history (
    id                                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    caller_block_catalog_code               bigint NOT NULL,
    caller_api_url                          bigint NOT NULL,
    caller_api_code                         varchar NOT NULL,
    caller_api_method                       bigint NOT NULL,
    caller_workflow_catalog_code            bigint NOT NULL,
    caller_workflow_catalog_version         bigint NOT NULL,
    caller_application_catalog_code         bigint NOT NULL,
    caller_application_catalog_version      bigint NOT NULL,
    caller_operator_type                    bigint NOT NULL,
    caller_operator_id                      varchar NOT NULL,
    pxr_id                                  varchar NOT NULL,
    caller_user_id                          varchar NOT NULL,
    temporary_code                          varchar NOT NULL,
    identity_code                           varchar NOT NULL,
    is_disabled                             boolean NOT NULL DEFAULT false,
    created_by                              varchar(255) NOT NULL,
    created_at                              timestamp without time zone NOT NULL DEFAULT now(),
    updated_by                              varchar(255) NOT NULL,
    updated_at                              timestamp without time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pxr_access_manage.caller_role (
    id                              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_history_id              bigint NOT NULL,
    caller_role_catalog_code        bigint NOT NULL,
    caller_role_catalog_version     bigint NOT NULL,
    is_disabled                     boolean NOT NULL DEFAULT false,
    created_by                      varchar(255) NOT NULL,
    created_at                      timestamp without time zone NOT NULL DEFAULT now(),
    updated_by                      varchar(255) NOT NULL,
    updated_at                      timestamp without time zone NOT NULL DEFAULT now()
);
