-- 移植：旧 pxr-access-control-service の各エンティティ（src/repositories/postgres/*Entity.ts）から組み立てた。
-- 旧実装は synchronize: false で、テーブルの DDL をリポジトリに持たないため、エンティティの定義から起こした。
-- 旧 MIT ライセンス（Copyright 2022 NEC Corporation）の表示は NOTICE を参照。
-- 旧 ormconfig の database は pxr_pod、schema は pxr_access_control。DB の作成は含まない。
-- TypeORM の既定（nullable 指定なし = NOT NULL）に従う。nullable: true の列だけ NULL 許容にした。

CREATE SCHEMA IF NOT EXISTS pxr_access_control;

CREATE TABLE IF NOT EXISTS pxr_access_control.api_access_permission (
    id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token                       varchar(255) NOT NULL,
    target_block_code           bigint,
    target_api_url              text NOT NULL,
    target_api_method           varchar(255) NOT NULL,
    target_user_id              varchar(255),
    expiration_date             timestamp without time zone NOT NULL,
    caller_block_code           bigint NOT NULL,
    caller_api_url              text NOT NULL,
    caller_api_method           varchar(255) NOT NULL,
    caller_api_code             varchar(255) NOT NULL,
    caller_wf_code              bigint,
    caller_wf_version           bigint,
    caller_app_code             bigint,
    caller_app_version          bigint,
    caller_operator_type        smallint NOT NULL,
    caller_operator_login_id    varchar(255) NOT NULL,
    parameter                   text NOT NULL,
    is_disabled                 boolean NOT NULL DEFAULT false,
    created_by                  varchar(255) NOT NULL,
    created_at                  timestamp without time zone NOT NULL DEFAULT NOW(),
    updated_by                  varchar(255) NOT NULL,
    updated_at                  timestamp without time zone NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS pxr_access_control.api_token (
    id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token                       varchar(255) NOT NULL,
    target_block_code           bigint,
    target_api_url              text NOT NULL,
    target_api_method           varchar(255) NOT NULL,
    target_user_id              varchar(255),
    expiration_date             timestamp without time zone NOT NULL,
    caller_block_code           bigint NOT NULL,
    caller_api_url              text NOT NULL,
    caller_api_method           varchar(255) NOT NULL,
    caller_api_code             varchar(255) NOT NULL,
    caller_wf_code              bigint,
    caller_wf_version           bigint,
    caller_app_code             bigint,
    caller_app_version          bigint,
    caller_operator_type        smallint NOT NULL,
    caller_operator_login_id    varchar(255) NOT NULL,
    attribute                   text,
    is_disabled                 boolean NOT NULL DEFAULT false,
    created_by                  varchar(255) NOT NULL,
    created_at                  timestamp without time zone NOT NULL DEFAULT NOW(),
    updated_by                  varchar(255) NOT NULL,
    updated_at                  timestamp without time zone NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS pxr_access_control.caller_role (
    id                              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    api_access_permission_id        bigint NOT NULL,
    role_catalog_code               bigint NOT NULL,
    role_catalog_version            bigint NOT NULL,
    is_disabled                     boolean NOT NULL DEFAULT false,
    created_by                      varchar(255) NOT NULL,
    created_at                      timestamp without time zone NOT NULL DEFAULT NOW(),
    updated_by                      varchar(255) NOT NULL,
    updated_at                      timestamp without time zone NOT NULL DEFAULT NOW()
);
