-- 移植：旧 pxr-block-proxy-service の ProxyLog エンティティ（src/repositories/postgres/ProxyLog.ts）から組み立てた。
-- 旧実装は synchronize: false で、テーブルの DDL をリポジトリに持たないため、エンティティの定義から起こした。
-- 旧 MIT ライセンス（Copyright 2022 NEC Corporation）の表示は NOTICE を参照。
-- 旧スキーマ（フェーズ1〜2）の仕様に合わせ、列名・型・NULL 制約は旧エンティティどおりにする。
-- 旧 ormconfig の database は pxr_pod、schema は pxr_block_proxy。DB の作成は含まない。

CREATE SCHEMA IF NOT EXISTS pxr_block_proxy;

CREATE TABLE IF NOT EXISTS pxr_block_proxy.log_called_api (
    id                               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type                             smallint NOT NULL,
    api_method                       varchar(255) NOT NULL,
    caller_block_catalog_code        bigint NOT NULL,
    caller_block_catalog_version     bigint NOT NULL,
    caller_api_url                   varchar(255) NOT NULL,
    destination_block_catalog_code   bigint NOT NULL,
    destination_block_catalog_version bigint NOT NULL,
    destination_api_url              varchar(255) NOT NULL,
    is_disabled                      boolean NOT NULL DEFAULT false,
    created_by                       varchar(255) NOT NULL,
    created_at                       timestamp without time zone NOT NULL DEFAULT now(),
    updated_by                       varchar(255) NOT NULL,
    updated_at                       timestamp without time zone NOT NULL DEFAULT now()
);
