-- 移植：旧 pxr-notification-service の各エンティティ（src/repositories/postgres/*.ts）から組み立てた。
-- 旧実装は synchronize: false で、テーブルの DDL をリポジトリに持たないため、エンティティの定義から起こした。
-- 旧 MIT ライセンス（Copyright 2022 NEC Corporation）の表示は NOTICE を参照。
-- 旧 ormconfig の database は pxr_pod、schema は pxr_notification。DB の作成は含まない。
-- TypeORM の既定（nullable 指定なし = NOT NULL）に従う。例外は下の注記。
--
-- 注記（エンティティの定義と、DDL の対応）
-- - 外部キー制約は起こしていない（他の単位と同じ扱い）。
-- - 旧 ormconfig の schema は pxr_notification。エンティティに nullable: true の列はない。要確認。
CREATE SCHEMA IF NOT EXISTS pxr_notification;

-- ApprovalManaged.ts
CREATE TABLE IF NOT EXISTS pxr_notification.approval_managed (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id       bigint NOT NULL,
    approver_operator_id  bigint NOT NULL,
    status                smallint NOT NULL DEFAULT 0,
    comment               varchar(255) NOT NULL,
    approval_at           timestamp without time zone NOT NULL,
    notice_block_code     bigint NOT NULL,
    notice_url            text NOT NULL,
    expiration_at         timestamp without time zone NOT NULL,
    is_disabled           boolean NOT NULL DEFAULT false,
    created_by            varchar(255) NOT NULL,
    created_at            timestamp without time zone NOT NULL DEFAULT now(),
    updated_by            varchar(255) NOT NULL,
    updated_at            timestamp without time zone NOT NULL DEFAULT now()
);

-- Notification.ts
CREATE TABLE IF NOT EXISTS pxr_notification.notification (
    id                        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type                      smallint NOT NULL,
    from_block_catalog_code   bigint NOT NULL,
    from_operator_id          bigint NOT NULL,
    from_actor_code           bigint NOT NULL,
    from_actor_version        bigint NOT NULL,
    to_block_catalog_code     bigint NOT NULL,
    to_operator_type          smallint NOT NULL,
    category_catalog_code     bigint NOT NULL,
    category_catalog_version  bigint NOT NULL,
    is_send_all               boolean NOT NULL DEFAULT false,
    title                     varchar(255) NOT NULL,
    content                   text NOT NULL,
    attributes                text NOT NULL DEFAULT '',
    send_at                   timestamp without time zone NOT NULL,
    is_transfer               boolean NOT NULL DEFAULT false,
    is_disabled               boolean NOT NULL DEFAULT false,
    created_by                varchar(255) NOT NULL,
    created_at                timestamp without time zone NOT NULL DEFAULT now(),
    updated_by                varchar(255) NOT NULL,
    updated_at                timestamp without time zone NOT NULL DEFAULT now()
);

-- NotificationDestination.ts
CREATE TABLE IF NOT EXISTS pxr_notification.notification_destination (
    id                       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id          bigint NOT NULL,
    destination_operator_id  bigint NOT NULL,
    destination_user_id      varchar(255) NOT NULL,
    actor_code               bigint NOT NULL,
    actor_version            bigint NOT NULL,
    is_disabled              boolean NOT NULL DEFAULT false,
    created_by               varchar(255) NOT NULL,
    created_at               timestamp without time zone NOT NULL DEFAULT now(),
    updated_by               varchar(255) NOT NULL,
    updated_at               timestamp without time zone NOT NULL DEFAULT now()
);

-- ReadFlagManagement.ts
CREATE TABLE IF NOT EXISTS pxr_notification.readflag_management (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id  bigint NOT NULL,
    operator_id      bigint NOT NULL,
    user_id          varchar(255) NOT NULL,
    read_at          timestamp without time zone NOT NULL DEFAULT 'now()',
    is_disabled      boolean NOT NULL DEFAULT false,
    created_by       varchar(255) NOT NULL,
    created_at       timestamp without time zone NOT NULL DEFAULT now(),
    updated_by       varchar(255) NOT NULL,
    updated_at       timestamp without time zone NOT NULL DEFAULT now()
);
