-- 移植：旧 pxr-identity-verificate-service の各エンティティ（src/repositories/postgres/*.ts）から組み立てた。
-- 旧実装は synchronize: false で、テーブルの DDL をリポジトリに持たないため、エンティティの定義から起こした。
-- 旧 MIT ライセンス（Copyright 2022 NEC Corporation）の表示は NOTICE を参照。
-- 旧 ormconfig の database は pxr_pod、schema は pxr_identify_verify。DB の作成は含まない。
-- TypeORM の既定（nullable 指定なし = NOT NULL）に従う。例外は下の注記。
--
-- 注記（エンティティの定義と、DDL の対応）
-- - 外部キー制約は起こしていない（他の単位と同じ扱い）。
-- - 旧 ormconfig の schema 名（pxr_identify_verify）は、旧リポジトリの設定のまま。単位名（identity-verify）とは綴りが違う。要確認。
CREATE SCHEMA IF NOT EXISTS pxr_identify_verify;

-- IdentifyVerifyEntity.ts
CREATE TABLE IF NOT EXISTS pxr_identify_verify.identify_verify (
    id                           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                         varchar(255) NOT NULL,
    actor_catalog_code           bigint NOT NULL,
    actor_catalog_version        bigint NOT NULL,
    region_catalog_code          bigint NOT NULL,
    region_catalog_version       bigint NOT NULL,
    application_catalog_code     bigint NOT NULL,
    application_catalog_version  bigint NOT NULL,
    workflow_catalog_code        bigint NOT NULL,
    workflow_catalog_version     bigint NOT NULL,
    pxr_id                       varchar(255) NOT NULL,
    user_id                      varchar(255) NOT NULL,
    is_verified                  smallint NOT NULL DEFAULT 0,
    expiration_at                timestamp without time zone NOT NULL,
    is_disabled                  boolean NOT NULL DEFAULT false,
    created_by                   varchar(255) NOT NULL,
    created_at                   timestamp without time zone NOT NULL DEFAULT now(),
    updated_by                   varchar(255) NOT NULL,
    updated_at                   timestamp without time zone NOT NULL DEFAULT now()
);

-- IdentifyVerifyUrlEntity.ts
CREATE TABLE IF NOT EXISTS pxr_identify_verify.identify_verify_url (
    id                           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                         varchar(255) NOT NULL,
    type                         smallint NOT NULL DEFAULT 0,
    user_id                      varchar(255) NOT NULL,
    actor_catalog_code           bigint NOT NULL,
    actor_catalog_version        bigint NOT NULL,
    region_catalog_code          bigint NOT NULL,
    region_catalog_version       bigint NOT NULL,
    application_catalog_code     bigint NOT NULL,
    application_catalog_version  bigint NOT NULL,
    workflow_catalog_code        bigint NOT NULL,
    workflow_catalog_version     bigint NOT NULL,
    expiration_at                timestamp without time zone NOT NULL,
    is_disabled                  boolean NOT NULL DEFAULT false,
    created_by                   varchar(255) NOT NULL,
    created_at                   timestamp without time zone NOT NULL DEFAULT now(),
    updated_by                   varchar(255) NOT NULL,
    updated_at                   timestamp without time zone NOT NULL DEFAULT now()
);
