-- 移植：旧 pxr-certification-authority-service の CertificateManageEntity（src/repositories/postgres/）から組み立てた。
-- 旧実装は synchronize: false で、テーブルの DDL をリポジトリに持たないため、エンティティの定義から起こした。
-- 旧 MIT ライセンス（Copyright 2022 NEC Corporation）の表示は NOTICE を参照。
-- 旧 ormconfig の database は pxr_pod、schema は pxr_certification_authority。DB の作成は含まない。
-- TypeORM の既定（nullable 指定なし = NOT NULL）に従う。nullable: true の列はない。

CREATE SCHEMA IF NOT EXISTS pxr_certification_authority;

CREATE TABLE IF NOT EXISTS pxr_certification_authority.certificate_manage (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cert_type               varchar(255) NOT NULL,
    subject                 text NOT NULL,
    serial_no               varchar(255) NOT NULL,
    finger_print            varchar(255) NOT NULL,
    valid_period_start      timestamp without time zone NOT NULL,
    valid_period_end        timestamp without time zone NOT NULL,
    certificate             text NOT NULL,
    actor_code              bigint NOT NULL,
    actor_version           bigint NOT NULL,
    block_code              bigint NOT NULL,
    block_version           bigint NOT NULL,
    is_distributed          boolean NOT NULL DEFAULT false,
    is_disabled             boolean NOT NULL DEFAULT false,
    created_by              varchar(255) NOT NULL,
    created_at              timestamp without time zone NOT NULL DEFAULT now(),
    updated_by              varchar(255) NOT NULL,
    updated_at              timestamp without time zone NOT NULL DEFAULT now()
);
