-- 移植：旧 pxr-catalog-service の各エンティティ（src/repositories/postgres/*Entity.ts）から組み立てた。
-- 旧実装は synchronize: false で、テーブルの DDL をリポジトリに持たないため、エンティティの定義から起こした。
-- 旧 MIT ライセンス（Copyright 2022 NEC Corporation）の表示は NOTICE を参照。
-- 旧 ormconfig の database は pxr_pod、schema は pxr_catalog。DB の作成は含まない。
-- TypeORM の既定（nullable 指定なし = NOT NULL）に従う。nullable: true の列だけ NULL 許容にした。
-- default: false / 0 の列は、エンティティの既定値を DEFAULT に写した。

CREATE SCHEMA IF NOT EXISTS pxr_catalog;

CREATE TABLE IF NOT EXISTS pxr_catalog.catalog (
    id                      varchar(255) PRIMARY KEY,
    name                    varchar(255) NOT NULL,
    description             text,
    ext_name                text NOT NULL,
    is_disabled             boolean NOT NULL DEFAULT false,
    attributes              text NOT NULL,
    created_by              varchar(255) NOT NULL,
    created_at              timestamp without time zone NOT NULL DEFAULT NOW(),
    updated_by              varchar(255) NOT NULL,
    updated_at              timestamp without time zone NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS pxr_catalog.catalog_item (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                    bigint NOT NULL,
    version                 bigint NOT NULL,
    ns_id                   bigint,
    name                    varchar(255),
    description             text,
    inherit_code            bigint,
    inherit_version         bigint,
    is_reserved             boolean NOT NULL DEFAULT false,
    is_disabled             boolean NOT NULL DEFAULT false,
    response                text,
    attributes              text,
    created_by              varchar(255) NOT NULL,
    created_at              timestamp without time zone NOT NULL DEFAULT NOW(),
    updated_by              varchar(255) NOT NULL,
    updated_at              timestamp without time zone NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS pxr_catalog.catalog_item_attribute (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    catalog_item_id         bigint,
    catalog_code            bigint,
    type                    smallint NOT NULL,
    key_code                bigint,
    key_version             bigint,
    ns_id                   bigint,
    value                   varchar(255),
    description             text,
    is_disabled             boolean NOT NULL DEFAULT false,
    created_by              varchar(255) NOT NULL,
    created_at              timestamp without time zone NOT NULL DEFAULT NOW(),
    updated_by              varchar(255) NOT NULL,
    updated_at              timestamp without time zone NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS pxr_catalog.catalog_relationship (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    catalog_item_id         bigint NOT NULL,
    ref_catalog_item_id     bigint NOT NULL,
    ref_type                varchar(255) NOT NULL,
    is_get_latest           boolean NOT NULL DEFAULT false,
    item_template_id        bigint,
    template_property_id    bigint,
    property_candidate_id   bigint,
    is_disabled             boolean NOT NULL DEFAULT false,
    attributes              text,
    created_by              varchar(255) NOT NULL,
    created_at              timestamp without time zone NOT NULL DEFAULT NOW(),
    updated_by              varchar(255) NOT NULL,
    updated_at              timestamp without time zone NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS pxr_catalog.catalog_code_scope (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type                    varchar(255) NOT NULL,
    start_code              bigint NOT NULL,
    end_code                bigint NOT NULL,
    is_disabled             boolean NOT NULL DEFAULT false,
    created_by              varchar(255) NOT NULL,
    created_at              timestamp without time zone NOT NULL DEFAULT NOW(),
    updated_by              varchar(255) NOT NULL,
    updated_at              timestamp without time zone NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS pxr_catalog.cmatrix_index (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    catalog_item_id         bigint NOT NULL,
    index_key               varchar(255) NOT NULL,
    value                   varchar(255),
    reserved                boolean NOT NULL DEFAULT false,
    is_disabled             boolean NOT NULL DEFAULT false,
    attributes              text,
    created_by              varchar(255) NOT NULL,
    created_at              timestamp without time zone NOT NULL DEFAULT NOW(),
    updated_by              varchar(255) NOT NULL,
    updated_at              timestamp without time zone NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS pxr_catalog.item_template (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    catalog_item_id         bigint,
    template_property_id    bigint,
    template                text,
    inner_name              varchar(255) NOT NULL,
    inner_inherit_code      bigint,
    inner_inherit_version   bigint,
    is_disabled             boolean NOT NULL DEFAULT false,
    response                text,
    attributes              text,
    created_by              varchar(255) NOT NULL,
    created_at              timestamp without time zone NOT NULL DEFAULT NOW(),
    updated_by              varchar(255) NOT NULL,
    updated_at              timestamp without time zone NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS pxr_catalog.ns (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type                    varchar(255),
    name                    text NOT NULL,
    description             text,
    is_disabled             boolean NOT NULL DEFAULT false,
    attributes              text,
    created_by              varchar(255) NOT NULL,
    created_at              timestamp without time zone NOT NULL DEFAULT NOW(),
    updated_by              varchar(255) NOT NULL,
    updated_at              timestamp without time zone NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS pxr_catalog.property_candidate (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_property_id    bigint NOT NULL,
    ns_id                   bigint,
    is_descendant           boolean NOT NULL DEFAULT false,
    code                    bigint,
    version                 bigint,
    base_code               bigint,
    base_version            bigint,
    value                   text,
    inners                  text,
    description             text,
    is_disabled             boolean NOT NULL DEFAULT false,
    created_by              varchar(255) NOT NULL,
    created_at              timestamp without time zone NOT NULL DEFAULT NOW(),
    updated_by              varchar(255) NOT NULL,
    updated_at              timestamp without time zone NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS pxr_catalog.template_code (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_property_id    bigint NOT NULL,
    code                    bigint,
    version                 bigint,
    is_disabled             boolean NOT NULL DEFAULT false,
    attributes              text,
    created_by              varchar(255) NOT NULL,
    created_at              timestamp without time zone NOT NULL DEFAULT NOW(),
    updated_by              varchar(255) NOT NULL,
    updated_at              timestamp without time zone NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS pxr_catalog.template_property (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_template_id        bigint NOT NULL,
    key_name                varchar(255) NOT NULL,
    type                    varchar(255) NOT NULL,
    code                    bigint,
    version                 bigint,
    filter                  varchar(255),
    index_key               varchar(255),
    format_code             bigint,
    format_version          bigint,
    unit_code               bigint,
    unit_version            bigint,
    description             text,
    is_disabled             boolean NOT NULL DEFAULT false,
    attributes              text,
    created_by              varchar(255) NOT NULL,
    created_at              timestamp without time zone NOT NULL DEFAULT NOW(),
    updated_by              varchar(255) NOT NULL,
    updated_at              timestamp without time zone NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS pxr_catalog.update_set (
    id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                        varchar(255) NOT NULL,
    description                 text,
    type                        smallint NOT NULL DEFAULT 0,
    caller_actor_code           bigint,
    caller_actor_version        bigint,
    approval_actor_code         bigint,
    approval_actor_version      bigint,
    approver                    varchar(255),
    approval_at                 timestamp without time zone,
    comment                     text,
    status                      smallint NOT NULL DEFAULT 0,
    register_actor_code         bigint,
    register_actor_version      bigint,
    register                    varchar(255),
    regist_at                   timestamp without time zone,
    appendix                    text,
    is_disabled                 boolean NOT NULL DEFAULT false,
    created_by                  varchar(255) NOT NULL,
    created_at                  timestamp without time zone NOT NULL DEFAULT NOW(),
    updated_by                  varchar(255) NOT NULL,
    updated_at                  timestamp without time zone NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS pxr_catalog.attribute_update_set (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    update_set_id           bigint NOT NULL,
    type                    smallint NOT NULL DEFAULT 0,
    catalog_code            bigint,
    comment                 text,
    attribute               text NOT NULL,
    is_disabled             boolean NOT NULL DEFAULT false,
    created_by              varchar(255) NOT NULL,
    created_at              timestamp without time zone NOT NULL DEFAULT NOW(),
    updated_by              varchar(255) NOT NULL,
    updated_at              timestamp without time zone NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS pxr_catalog.catalog_update_set (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    update_set_id           bigint NOT NULL,
    type                    smallint NOT NULL DEFAULT 0,
    catalog_item_id         bigint,
    catalog_item_code       bigint,
    comment                 text,
    template                text NOT NULL,
    is_disabled             boolean NOT NULL DEFAULT false,
    created_by              varchar(255) NOT NULL,
    created_at              timestamp without time zone NOT NULL DEFAULT NOW(),
    updated_by              varchar(255) NOT NULL,
    updated_at              timestamp without time zone NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS pxr_catalog.ns_update_set (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    update_set_id           bigint NOT NULL,
    type                    smallint NOT NULL DEFAULT 0,
    ns_id                   bigint,
    comment                 text,
    template                text NOT NULL,
    is_disabled             boolean NOT NULL DEFAULT false,
    created_by              varchar(255) NOT NULL,
    created_at              timestamp without time zone NOT NULL DEFAULT NOW(),
    updated_by              varchar(255) NOT NULL,
    updated_at              timestamp without time zone NOT NULL DEFAULT NOW()
);
