-- 移植：旧 pxr-operator-service の各エンティティ（src/repositories/postgres/*Entity.ts、*.ts）から組み立てた。
-- 旧実装は synchronize: false で、テーブルの DDL をリポジトリに持たないため、エンティティの定義から起こした。
-- 旧 MIT ライセンス（Copyright 2022 NEC Corporation）の表示は NOTICE を参照。
-- 旧 ormconfig の database は pxr_pod、schema は pxr_operator。DB の作成は含まない。
-- TypeORM の既定（nullable 指定なし = NOT NULL）に従う。例外は下の注記。
--
-- 注記（エンティティの定義と、DDL の対応）
-- - operator.lock_start_at、operator.password_updated_at：エンティティは default: null のみ指定。NULL 許容とした。
-- - sms_verification_code.operator_id：エンティティの型は number だが、列の型は varchar(255)。列の型に合わせた。

CREATE SCHEMA IF NOT EXISTS pxr_operator;

CREATE TABLE IF NOT EXISTS pxr_operator.operator (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type                    smallint NOT NULL DEFAULT 0,
    login_id                varchar(255) NOT NULL,
    hpassword               varchar(255) NOT NULL,
    pxr_id                  varchar(255) NOT NULL,
    user_information        text NOT NULL,
    name                    varchar(255) NOT NULL,
    mobile_phone            varchar(255) NOT NULL,
    mail                    varchar(255) NOT NULL,
    auth                    text NOT NULL,
    last_login_at           timestamp without time zone NOT NULL DEFAULT now(),
    password_changed_flg    boolean NOT NULL DEFAULT false,
    login_prohibited_flg    boolean NOT NULL DEFAULT false,
    attributes              text NOT NULL,
    lock_flg                boolean NOT NULL,
    lock_start_at           timestamp without time zone,
    password_updated_at     timestamp without time zone,
    user_id                 varchar(255) NOT NULL,
    region_catalog_code     bigint NOT NULL,
    app_catalog_code        bigint NOT NULL,
    wf_catalog_code         bigint NOT NULL,
    client_id               varchar(255) NOT NULL,
    is_disabled             boolean NOT NULL DEFAULT false,
    created_by              varchar(255) NOT NULL,
    created_at              timestamp without time zone NOT NULL DEFAULT now(),
    updated_by              varchar(255) NOT NULL,
    updated_at              timestamp without time zone NOT NULL DEFAULT now(),
    unique_check_login_id   text NOT NULL
);

CREATE TABLE IF NOT EXISTS pxr_operator.session (
    id              varchar(255) PRIMARY KEY,
    operator_id     bigint NOT NULL,
    expire_at       timestamp without time zone NOT NULL DEFAULT now(),
    is_disabled     boolean NOT NULL DEFAULT false,
    created_by      varchar(255) NOT NULL,
    created_at      timestamp without time zone NOT NULL DEFAULT now(),
    updated_by      varchar(255) NOT NULL,
    updated_at      timestamp without time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pxr_operator.user_information (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operator_id         bigint NOT NULL,
    catalog_code        bigint NOT NULL,
    catalog_version     bigint NOT NULL,
    value               text NOT NULL,
    is_disabled         boolean NOT NULL DEFAULT false,
    created_by          varchar(255) NOT NULL,
    created_at          timestamp without time zone NOT NULL DEFAULT now(),
    updated_by          varchar(255) NOT NULL,
    updated_at          timestamp without time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pxr_operator.role_setting (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operator_id             bigint NOT NULL,
    role_catalog_code       bigint NOT NULL,
    role_catalog_version    bigint NOT NULL,
    is_disabled             boolean NOT NULL DEFAULT false,
    created_by              varchar(255) NOT NULL,
    created_at              timestamp without time zone NOT NULL DEFAULT now(),
    updated_by              varchar(255) NOT NULL,
    updated_at              timestamp without time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pxr_operator.manage_block_info (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_code      bigint NOT NULL,
    actor_version   bigint NOT NULL,
    is_disabled     boolean NOT NULL DEFAULT false,
    created_by      varchar(255) NOT NULL,
    created_at      timestamp without time zone NOT NULL DEFAULT now(),
    updated_by      varchar(255) NOT NULL,
    updated_at      timestamp without time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pxr_operator.login_history (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operator_id     bigint NOT NULL,
    login_at        timestamp without time zone NOT NULL,
    result          boolean NOT NULL DEFAULT false,
    is_disabled     boolean NOT NULL DEFAULT false,
    created_by      varchar(255) NOT NULL,
    created_at      timestamp without time zone NOT NULL DEFAULT now(),
    updated_by      varchar(255) NOT NULL,
    updated_at      timestamp without time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pxr_operator.password_history (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operator_id     bigint NOT NULL,
    hpassword       varchar(255) NOT NULL,
    is_disabled     boolean NOT NULL DEFAULT false,
    created_by      varchar(255) NOT NULL,
    created_at      timestamp without time zone NOT NULL DEFAULT now(),
    updated_by      varchar(255) NOT NULL,
    updated_at      timestamp without time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pxr_operator.identify_code (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            varchar(255) NOT NULL,
    pxr_id          varchar(255) NOT NULL,
    expiration_at   timestamp without time zone NOT NULL,
    is_disabled     boolean NOT NULL DEFAULT false,
    created_by      varchar(255) NOT NULL,
    created_at      timestamp without time zone NOT NULL DEFAULT now(),
    updated_by      varchar(255) NOT NULL,
    updated_at      timestamp without time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pxr_operator.one_time_login_code (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            varchar(255) NOT NULL,
    operator_id     bigint NOT NULL,
    expire_at       timestamp without time zone NOT NULL DEFAULT now(),
    created_by      varchar(255) NOT NULL,
    created_at      timestamp without time zone NOT NULL DEFAULT now(),
    updated_by      varchar(255) NOT NULL,
    updated_at      timestamp without time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pxr_operator.sms_verification_code (
    id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operator_id                 varchar(255) NOT NULL,
    verification_code           varchar(255) NOT NULL,
    verification_code_expiration timestamp without time zone NOT NULL,
    verification_result         smallint NOT NULL,
    is_disabled                 boolean NOT NULL DEFAULT false,
    created_by                  varchar(255) NOT NULL,
    created_at                  timestamp without time zone NOT NULL DEFAULT now(),
    updated_by                  varchar(255) NOT NULL,
    updated_at                  timestamp without time zone NOT NULL DEFAULT now()
);
