// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
	"time"
)

type PxrOperatorIdentifyCode struct {
	ID           int64
	Code         string
	PxrID        string
	ExpirationAt time.Time
	IsDisabled   bool
	CreatedBy    string
	CreatedAt    time.Time
	UpdatedBy    string
	UpdatedAt    time.Time
}

type PxrOperatorLoginHistory struct {
	ID         int64
	OperatorID int64
	LoginAt    time.Time
	Result     bool
	IsDisabled bool
	CreatedBy  string
	CreatedAt  time.Time
	UpdatedBy  string
	UpdatedAt  time.Time
}

type PxrOperatorManageBlockInfo struct {
	ID           int64
	ActorCode    int64
	ActorVersion int64
	IsDisabled   bool
	CreatedBy    string
	CreatedAt    time.Time
	UpdatedBy    string
	UpdatedAt    time.Time
}

type PxrOperatorOneTimeLoginCode struct {
	ID         int64
	Code       string
	OperatorID int64
	ExpireAt   time.Time
	CreatedBy  string
	CreatedAt  time.Time
	UpdatedBy  string
	UpdatedAt  time.Time
}

type PxrOperatorOperator struct {
	ID                 int64
	Type               int16
	LoginID            string
	Hpassword          string
	PxrID              string
	UserInformation    string
	Name               string
	MobilePhone        string
	Mail               string
	Auth               string
	LastLoginAt        time.Time
	PasswordChangedFlg bool
	LoginProhibitedFlg bool
	Attributes         string
	LockFlg            bool
	LockStartAt        sql.NullTime
	PasswordUpdatedAt  sql.NullTime
	UserID             string
	RegionCatalogCode  int64
	AppCatalogCode     int64
	WfCatalogCode      int64
	ClientID           string
	IsDisabled         bool
	CreatedBy          string
	CreatedAt          time.Time
	UpdatedBy          string
	UpdatedAt          time.Time
	UniqueCheckLoginID string
}

type PxrOperatorPasswordHistory struct {
	ID         int64
	OperatorID int64
	Hpassword  string
	IsDisabled bool
	CreatedBy  string
	CreatedAt  time.Time
	UpdatedBy  string
	UpdatedAt  time.Time
}

type PxrOperatorRoleSetting struct {
	ID                 int64
	OperatorID         int64
	RoleCatalogCode    int64
	RoleCatalogVersion int64
	IsDisabled         bool
	CreatedBy          string
	CreatedAt          time.Time
	UpdatedBy          string
	UpdatedAt          time.Time
}

type PxrOperatorSession struct {
	ID         string
	OperatorID int64
	ExpireAt   time.Time
	IsDisabled bool
	CreatedBy  string
	CreatedAt  time.Time
	UpdatedBy  string
	UpdatedAt  time.Time
}

type PxrOperatorSmsVerificationCode struct {
	ID                         int64
	OperatorID                 string
	VerificationCode           string
	VerificationCodeExpiration time.Time
	VerificationResult         int16
	IsDisabled                 bool
	CreatedBy                  string
	CreatedAt                  time.Time
	UpdatedBy                  string
	UpdatedAt                  time.Time
}

type PxrOperatorUserInformation struct {
	ID             int64
	OperatorID     int64
	CatalogCode    int64
	CatalogVersion int64
	Value          string
	IsDisabled     bool
	CreatedBy      string
	CreatedAt      time.Time
	UpdatedBy      string
	UpdatedAt      time.Time
}
