// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package store

import (
	"context"
)

const findOperatorByID = `-- name: FindOperatorByID :one

SELECT id, pxr_id
FROM pxr_operator.operator
WHERE id = $1
`

type FindOperatorByIDRow struct {
	ID    int64
	PxrID string
}

// 見本のクエリ。旧スキーマ pxr_operator の表を読むだけで、書き込みはしない。
// 機密の列（hpassword など）と個人情報（name、mobile_phone、mail）は、見本でも選ばない。
func (q *Queries) FindOperatorByID(ctx context.Context, id int64) (FindOperatorByIDRow, error) {
	row := q.db.QueryRowContext(ctx, findOperatorByID, id)
	var i FindOperatorByIDRow
	err := row.Scan(&i.ID, &i.PxrID)
	return i, err
}
