-- 移植：旧 pxr-book-manage-service の各エンティティ（src/repositories/postgres/*.ts）から組み立てた。
-- 旧実装は synchronize: false で、テーブルの DDL をリポジトリに持たないため、エンティティの定義から起こした。
-- 旧 MIT ライセンス（Copyright 2022 NEC Corporation）の表示は NOTICE を参照。
-- 旧 ormconfig の database は pxr_pod、schema は pxr_book_manage。DB の作成は含まない。
-- TypeORM の既定（nullable 指定なし = NOT NULL）に従う。nullable: true の列はない。
--
-- 注記（エンティティの定義と、DDL の対応）
-- - 外部キー制約は起こしていない（他の単位と同じ扱い）。
-- - temporarily_shared_code.id：PrimaryGeneratedColumn('uuid') を uuid と DEFAULT gen_random_uuid() で表した（PostgreSQL 13 以降）。
-- - temporarily_shared_code.updated_at：エンティティは CreateDateColumn のため、更新時の自動更新は持たない。
-- - nullable 指定のない列は、TypeORM の既定どおり NOT NULL。実環境で NULL を許していれば差分になる。要確認。

CREATE SCHEMA IF NOT EXISTS pxr_book_manage;

-- DataOperation.ts
CREATE TABLE IF NOT EXISTS pxr_book_manage.data_operation (
    id                         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id                    bigint NOT NULL,
    region_use_id              bigint NOT NULL,
    type                       varchar(255) NOT NULL,
    operation_catalog_code     bigint NOT NULL,
    operation_catalog_version  bigint NOT NULL,
    actor_catalog_code         bigint NOT NULL,
    actor_catalog_version      bigint NOT NULL,
    app_catalog_code           bigint NOT NULL,
    app_catalog_version        bigint NOT NULL,
    wf_catalog_code            bigint NOT NULL,
    wf_catalog_version         bigint NOT NULL,
    attributes                 text NOT NULL,
    is_disabled                boolean NOT NULL DEFAULT false,
    created_by                 varchar(255) NOT NULL,
    created_at                 timestamp without time zone NOT NULL DEFAULT now(),
    updated_by                 varchar(255) NOT NULL,
    updated_at                 timestamp without time zone NOT NULL DEFAULT now()
);

-- DataOperationDataType.ts
CREATE TABLE IF NOT EXISTS pxr_book_manage.data_operation_data_type (
    id                        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_operation_id         bigint NOT NULL,
    catalog_uuid              varchar(255) NOT NULL,
    document_catalog_code     bigint NOT NULL,
    document_catalog_version  bigint NOT NULL,
    event_catalog_code        bigint NOT NULL,
    event_catalog_version     bigint NOT NULL,
    thing_catalog_code        bigint NOT NULL,
    thing_catalog_version     bigint NOT NULL,
    consent_flg               boolean NOT NULL DEFAULT true,
    attributes                text NOT NULL,
    is_disabled               boolean NOT NULL DEFAULT false,
    created_by                varchar(255) NOT NULL,
    created_at                timestamp without time zone NOT NULL DEFAULT now(),
    updated_by                varchar(255) NOT NULL,
    updated_at                timestamp without time zone NOT NULL DEFAULT now()
);

-- DataOperationNotification.ts
CREATE TABLE IF NOT EXISTS pxr_book_manage.data_operation_notification (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    _value       bigint NOT NULL,
    _ver         bigint NOT NULL,
    status       smallint NOT NULL DEFAULT 0,
    is_disabled  boolean NOT NULL DEFAULT false,
    created_by   varchar(255) NOT NULL,
    created_at   timestamp without time zone NOT NULL DEFAULT now(),
    updated_by   varchar(255) NOT NULL,
    updated_at   timestamp without time zone NOT NULL DEFAULT now()
);

-- DataOperationNotificationInd.ts
CREATE TABLE IF NOT EXISTS pxr_book_manage.data_operation_notification_ind (
    id                              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_operation_notification_id  bigint NOT NULL,
    book_id                         bigint NOT NULL,
    status                          smallint NOT NULL DEFAULT 0,
    last_sent_at                    timestamp without time zone NOT NULL,
    is_disabled                     boolean NOT NULL DEFAULT false,
    created_by                      varchar(255) NOT NULL,
    created_at                      timestamp without time zone NOT NULL DEFAULT now(),
    updated_by                      varchar(255) NOT NULL,
    updated_at                      timestamp without time zone NOT NULL DEFAULT now()
);

-- DetaOperationData.ts
CREATE TABLE IF NOT EXISTS pxr_book_manage.data_operation_data (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_operation_id  bigint NOT NULL,
    parent_data_id     varchar(255) NOT NULL,
    type               smallint NOT NULL,
    identifier         varchar(255) NOT NULL,
    attributes         text NOT NULL,
    is_disabled        boolean NOT NULL DEFAULT false,
    created_by         varchar(255) NOT NULL,
    created_at         timestamp without time zone NOT NULL DEFAULT now(),
    updated_by         varchar(255) NOT NULL,
    updated_at         timestamp without time zone NOT NULL DEFAULT now()
);

-- Identification.ts
CREATE TABLE IF NOT EXISTS pxr_book_manage.identification (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id                 bigint NOT NULL,
    identification_code     bigint NOT NULL,
    identification_version  bigint NOT NULL,
    template                text NOT NULL,
    template_hash           varchar(255) NOT NULL,
    is_disabled             boolean NOT NULL DEFAULT false,
    created_by              varchar(255) NOT NULL,
    created_at              timestamp without time zone NOT NULL DEFAULT now(),
    updated_by              varchar(255) NOT NULL,
    updated_at              timestamp without time zone NOT NULL DEFAULT now()
);

-- McdAlteration.ts
CREATE TABLE IF NOT EXISTS pxr_book_manage.mcd_alteration (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id                 bigint NOT NULL,
    actor_catalog_code      bigint NOT NULL,
    actor_catalog_version   bigint NOT NULL,
    region_catalog_code     bigint NOT NULL,
    region_catalog_version  bigint NOT NULL,
    alteration              text NOT NULL,
    is_disabled             boolean NOT NULL DEFAULT false,
    created_by              varchar(255) NOT NULL,
    created_at              timestamp without time zone NOT NULL DEFAULT now(),
    updated_by              varchar(255) NOT NULL,
    updated_at              timestamp without time zone NOT NULL DEFAULT now()
);

-- McdAlterationActor.ts
CREATE TABLE IF NOT EXISTS pxr_book_manage.mcd_alteration_actor (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mcd_alteration_id      bigint NOT NULL,
    target_term_start      timestamp without time zone NOT NULL,
    target_term_end        timestamp without time zone NOT NULL,
    actor_catalog_code     bigint NOT NULL,
    actor_catalog_version  bigint NOT NULL,
    app_catalog_code       bigint NOT NULL,
    app_catalog_version    bigint NOT NULL,
    wf_catalog_code        bigint NOT NULL,
    wf_catalog_version     bigint NOT NULL,
    alteration             text NOT NULL,
    approval_status        smallint NOT NULL,
    message                text NOT NULL,
    is_disabled            boolean NOT NULL DEFAULT false,
    created_by             varchar(255) NOT NULL,
    created_at             timestamp without time zone NOT NULL DEFAULT now(),
    updated_by             varchar(255) NOT NULL,
    updated_at             timestamp without time zone NOT NULL DEFAULT now()
);

-- McdAlterationData.ts
CREATE TABLE IF NOT EXISTS pxr_book_manage.mcd_alteration_data (
    id                        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mcd_alteration_actor_id   bigint NOT NULL,
    document_catalog_code     bigint NOT NULL,
    document_catalog_version  bigint NOT NULL,
    document_id               varchar(255) NOT NULL,
    event_catalog_code        bigint NOT NULL,
    event_catalog_version     bigint NOT NULL,
    event_id                  varchar(255) NOT NULL,
    thing_catalog_code        bigint NOT NULL,
    thing_catalog_version     bigint NOT NULL,
    thing_id                  varchar(255) NOT NULL,
    is_disabled               boolean NOT NULL DEFAULT false,
    created_by                varchar(255) NOT NULL,
    created_at                timestamp without time zone NOT NULL DEFAULT now(),
    updated_by                varchar(255) NOT NULL,
    updated_at                timestamp without time zone NOT NULL DEFAULT now()
);

-- McdOutputCodeActor.ts
CREATE TABLE IF NOT EXISTS pxr_book_manage.mcd_output_code_actor (
    id                        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mcd_output_code_id        bigint NOT NULL,
    target_term_start         timestamp without time zone NOT NULL,
    target_term_end           timestamp without time zone NOT NULL,
    actor_catalog_code        bigint NOT NULL,
    actor_catalog_version     bigint NOT NULL,
    app_catalog_code          bigint NOT NULL,
    app_catalog_version       bigint NOT NULL,
    wf_catalog_code           bigint NOT NULL,
    wf_catalog_version        bigint NOT NULL,
    ind_request               varchar(255) NOT NULL,
    release_cooperate_spec    smallint NOT NULL,
    release_cooperate_status  smallint NOT NULL,
    return_data_spec          smallint NOT NULL DEFAULT 0,
    approval_status           smallint NOT NULL,
    message                   text NOT NULL,
    delete_data_spec          smallint NOT NULL DEFAULT 0,
    is_disabled               boolean NOT NULL DEFAULT false,
    created_by                varchar(255) NOT NULL,
    created_at                timestamp without time zone NOT NULL DEFAULT now(),
    updated_by                varchar(255) NOT NULL,
    updated_at                timestamp without time zone NOT NULL DEFAULT now()
);

-- McdOutputCodeDataFile.ts
CREATE TABLE IF NOT EXISTS pxr_book_manage.mcd_output_code_data_file (
    id                             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mcd_output_code_actor_id       bigint NOT NULL,
    mcd_output_code                varchar(255) NOT NULL,
    actor_catalog_code             bigint NOT NULL,
    actor_catalog_version          bigint NOT NULL,
    output_data_approval_status    smallint NOT NULL,
    output_file_type               smallint NOT NULL,
    upload_file_type               smallint NOT NULL,
    notification_status            smallint NOT NULL,
    file_name                      varchar(255) NOT NULL,
    input_file_preparation_status  smallint NOT NULL,
    output_status                  smallint NOT NULL,
    delete_data_spec               smallint NOT NULL,
    delete_status                  smallint NOT NULL,
    is_processing                  boolean NOT NULL DEFAULT false,
    is_disabled                    boolean NOT NULL DEFAULT false,
    created_by                     varchar(255) NOT NULL,
    created_at                     timestamp without time zone NOT NULL DEFAULT now(),
    updated_by                     varchar(255) NOT NULL,
    updated_at                     timestamp without time zone NOT NULL DEFAULT now()
);

-- McdOutputCodeDataType.ts
CREATE TABLE IF NOT EXISTS pxr_book_manage.mcd_output_code_data_type (
    id                        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mcd_output_code_actor_id  bigint NOT NULL,
    document_catalog_code     bigint NOT NULL,
    document_catalog_version  bigint NOT NULL,
    document_id               varchar(255) NOT NULL,
    event_catalog_code        bigint NOT NULL,
    event_catalog_version     bigint NOT NULL,
    event_id                  varchar(255) NOT NULL,
    thing_catalog_code        bigint NOT NULL,
    thing_catalog_version     bigint NOT NULL,
    thing_id                  varchar(255) NOT NULL,
    is_disabled               boolean NOT NULL DEFAULT false,
    created_by                varchar(255) NOT NULL,
    created_at                timestamp without time zone NOT NULL DEFAULT now(),
    updated_by                varchar(255) NOT NULL,
    updated_at                timestamp without time zone NOT NULL DEFAULT now()
);

-- MyConditionBook.ts
CREATE TABLE IF NOT EXISTS pxr_book_manage.my_condition_book (
    id                       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pxr_id                   varchar(255) NOT NULL,
    status                   bigint NOT NULL DEFAULT 0,
    book_close_available     boolean NOT NULL DEFAULT false,
    book_close_available_at  timestamp without time zone NOT NULL DEFAULT now(),
    attributes               text NOT NULL,
    appendix                 text NOT NULL,
    force_deletion_flag      boolean NOT NULL DEFAULT false,
    is_disabled              boolean NOT NULL DEFAULT false,
    created_by               varchar(255) NOT NULL,
    created_at               timestamp without time zone NOT NULL DEFAULT now(),
    updated_by               varchar(255) NOT NULL,
    updated_at               timestamp without time zone NOT NULL DEFAULT now()
);

-- MyConditionDataOutputCode.ts
CREATE TABLE IF NOT EXISTS pxr_book_manage.my_condition_data_output_code (
    id                                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                               varchar(255) NOT NULL,
    book_id                            bigint NOT NULL,
    output_type                        bigint NOT NULL,
    actor_catalog_code                 bigint NOT NULL,
    actor_catalog_version              bigint NOT NULL,
    region_catalog_code                bigint NOT NULL,
    region_catalog_version             bigint NOT NULL,
    app_catalog_code                   bigint NOT NULL,
    app_catalog_version                bigint NOT NULL,
    wf_catalog_code                    bigint NOT NULL,
    wf_catalog_version                 bigint NOT NULL,
    bucket_name                        varchar NOT NULL,
    presigned_url_expire_at            timestamp without time zone NOT NULL,
    presigned_url_status               smallint NOT NULL,
    release_cooperate_approval_status  smallint NOT NULL,
    release_cooperate_status           smallint NOT NULL,
    release_service_cooperate_status   smallint NOT NULL,
    is_processing                      boolean NOT NULL DEFAULT false,
    is_disabled                        boolean NOT NULL DEFAULT false,
    created_by                         varchar(255) NOT NULL,
    created_at                         timestamp without time zone NOT NULL DEFAULT now(),
    updated_by                         varchar(255) NOT NULL,
    updated_at                         timestamp without time zone NOT NULL DEFAULT now()
);

-- ShareSourceDatatype.ts
CREATE TABLE IF NOT EXISTS pxr_book_manage.share_source_datatype (
    id                         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_event_notificate_id  bigint NOT NULL,
    share_catalog_code         bigint NOT NULL,
    share_catalog_version      bigint NOT NULL,
    share_uuid                 varchar(255) NOT NULL,
    document_catalog_code      bigint NOT NULL,
    document_catalog_version   bigint NOT NULL,
    event_catalog_code         bigint NOT NULL,
    event_catalog_version      bigint NOT NULL,
    thing_catalog_code         bigint NOT NULL,
    thing_catalog_version      bigint NOT NULL,
    is_disabled                boolean NOT NULL DEFAULT false,
    created_by                 varchar(255) NOT NULL,
    created_at                 timestamp without time zone NOT NULL DEFAULT now(),
    updated_by                 varchar(255) NOT NULL,
    updated_at                 timestamp without time zone NOT NULL DEFAULT now()
);

-- ShareSourceSource.ts
CREATE TABLE IF NOT EXISTS pxr_book_manage.share_source_source (
    id                        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    share_source_datatype_id  bigint NOT NULL,
    actor_catalog_code        bigint NOT NULL,
    actor_catalog_version     bigint NOT NULL,
    is_disabled               boolean NOT NULL DEFAULT false,
    created_by                varchar(255) NOT NULL,
    created_at                timestamp without time zone NOT NULL DEFAULT now(),
    updated_by                varchar(255) NOT NULL,
    updated_at                timestamp without time zone NOT NULL DEFAULT now()
);

-- StoppedRegion.ts
CREATE TABLE IF NOT EXISTS pxr_book_manage.stopped_region (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_catalog_code      bigint NOT NULL,
    actor_catalog_version   bigint NOT NULL,
    region_catalog_code     bigint NOT NULL,
    region_catalog_version  bigint NOT NULL,
    closed_at               timestamp without time zone NOT NULL,
    is_disabled             boolean NOT NULL DEFAULT false,
    created_by              varchar(255) NOT NULL,
    created_at              timestamp without time zone NOT NULL DEFAULT now(),
    updated_by              varchar(255) NOT NULL,
    updated_at              timestamp without time zone NOT NULL DEFAULT now()
);

-- StoreEventNotificate.ts
CREATE TABLE IF NOT EXISTS pxr_book_manage.store_event_notificate (
    id                                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notificate_type                         varchar(255) NOT NULL,
    store_event_notificate_catalog_code     bigint NOT NULL,
    store_event_notificate_catalog_version  bigint NOT NULL,
    share_catalog_code                      bigint NOT NULL,
    share_catalog_version                   bigint NOT NULL,
    share_uuid                              varchar(255) NOT NULL,
    is_disabled                             boolean NOT NULL DEFAULT false,
    created_by                              varchar(255) NOT NULL,
    created_at                              timestamp without time zone NOT NULL DEFAULT now(),
    updated_by                              varchar(255) NOT NULL,
    updated_at                              timestamp without time zone NOT NULL DEFAULT now()
);

-- StoreEventNotificateHistory.ts
CREATE TABLE IF NOT EXISTS pxr_book_manage.store_event_notificate_history (
    id                                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notificate_type                     varchar(255) NOT NULL,
    process_type                        varchar(255) NOT NULL,
    user_id                             varchar(255) NOT NULL,
    data_id                             varchar(255) NOT NULL,
    document_catalog_code               bigint NOT NULL,
    document_catalog_version            bigint NOT NULL,
    event_catalog_code                  bigint NOT NULL,
    event_catalog_version               bigint NOT NULL,
    thing_catalog_code                  bigint NOT NULL,
    thing_catalog_version               bigint NOT NULL,
    share_source_actor_catalog_code     bigint NOT NULL,
    share_source_actor_catalog_version  bigint NOT NULL,
    share_source_app_catalog_code       bigint NOT NULL,
    share_source_app_catalog_version    bigint NOT NULL,
    share_source_wf_catalog_code        bigint NOT NULL,
    share_source_wf_catalog_version     bigint NOT NULL,
    share_target_actor_catalog_code     bigint NOT NULL,
    share_target_actor_catalog_version  bigint NOT NULL,
    share_target_app_catalog_code       bigint NOT NULL,
    share_target_app_catalog_version    bigint NOT NULL,
    share_target_wf_catalog_code        bigint NOT NULL,
    share_target_wf_catalog_version     bigint NOT NULL,
    is_disabled                         boolean NOT NULL DEFAULT false,
    created_by                          varchar(255) NOT NULL,
    created_at                          timestamp without time zone NOT NULL DEFAULT now(),
    updated_by                          varchar(255) NOT NULL,
    updated_at                          timestamp without time zone NOT NULL DEFAULT now()
);

-- TemporarilySharedCode.ts
CREATE TABLE IF NOT EXISTS pxr_book_manage.temporarily_shared_code (
    id                          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    data_operate_definition_id  bigint NOT NULL,
    expire_at                   timestamp without time zone NOT NULL,
    is_disabled                 boolean NOT NULL DEFAULT false,
    created_by                  varchar(255) NOT NULL,
    created_at                  timestamp without time zone NOT NULL DEFAULT now(),
    updated_by                  varchar(255) NOT NULL,
    updated_at                  timestamp without time zone NOT NULL DEFAULT now()
);

-- TermsOfUseNotification.ts
CREATE TABLE IF NOT EXISTS pxr_book_manage.terms_of_use_notification (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    terms_type   bigint NOT NULL,
    _value       bigint NOT NULL,
    _ver         bigint NOT NULL,
    status       bigint NOT NULL,
    is_disabled  boolean NOT NULL DEFAULT false,
    created_by   varchar(255) NOT NULL,
    created_at   timestamp without time zone NOT NULL DEFAULT now(),
    updated_by   varchar(255) NOT NULL,
    updated_at   timestamp without time zone NOT NULL DEFAULT now()
);

-- TermsOfUseNotificationInd.ts
CREATE TABLE IF NOT EXISTS pxr_book_manage.terms_of_use_notification_ind (
    id                            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    terms_of_use_notification_id  bigint NOT NULL,
    book_id                       bigint NOT NULL,
    status                        smallint NOT NULL DEFAULT 0,
    last_sent_at                  timestamp without time zone NOT NULL,
    is_disabled                   boolean NOT NULL DEFAULT false,
    created_by                    varchar(255) NOT NULL,
    created_at                    timestamp without time zone NOT NULL DEFAULT now(),
    updated_by                    varchar(255) NOT NULL,
    updated_at                    timestamp without time zone NOT NULL DEFAULT now()
);

-- TouConsent.ts
CREATE TABLE IF NOT EXISTS pxr_book_manage.tou_consent (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id               bigint NOT NULL,
    terms_type            bigint NOT NULL,
    terms_of_use_code     bigint NOT NULL,
    terms_of_use_version  bigint NOT NULL,
    is_disabled           boolean NOT NULL DEFAULT false,
    created_by            varchar(255) NOT NULL,
    created_at            timestamp without time zone NOT NULL DEFAULT now(),
    updated_by            varchar(255) NOT NULL,
    updated_at            timestamp without time zone NOT NULL DEFAULT now()
);

-- UserIdCooperate.ts
CREATE TABLE IF NOT EXISTS pxr_book_manage.user_id_cooperate (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id                 bigint NOT NULL,
    actor_catalog_code      bigint NOT NULL,
    actor_catalog_version   bigint NOT NULL,
    region_catalog_code     bigint NOT NULL,
    region_catalog_version  bigint NOT NULL,
    app_catalog_code        bigint NOT NULL,
    app_catalog_version     bigint NOT NULL,
    wf_catalog_code         bigint NOT NULL,
    wf_catalog_version      bigint NOT NULL,
    user_id                 varchar(255) NOT NULL,
    status                  smallint NOT NULL,
    start_at                timestamp without time zone NOT NULL,
    is_disabled             boolean NOT NULL DEFAULT false,
    created_by              varchar(255) NOT NULL,
    created_at              timestamp without time zone NOT NULL DEFAULT now(),
    updated_by              varchar(255) NOT NULL,
    updated_at              timestamp without time zone NOT NULL DEFAULT now()
);
