-- 移植：旧 pxr-binary-manage-service の各エンティティ（src/repositories/postgres/*.ts）から組み立てた。
-- 旧実装は synchronize: false で、テーブルの DDL をリポジトリに持たないため、エンティティの定義から起こした。
-- 旧 MIT ライセンス（Copyright 2022 NEC Corporation）の表示は NOTICE を参照。
-- 旧 ormconfig の database は pxr_pod、schema は pxr_binary_manage。DB の作成は含まない。
-- TypeORM の既定（nullable 指定なし = NOT NULL）に従う。nullable: true の列はない。
--
-- 注記（エンティティの定義と、DDL の対応）
-- - 外部キー制約は起こしていない（他の単位と同じ扱い）。
-- - file_upload_manage.id は @PrimaryColumn（文字列）で、主キーとした。
-- - file_upload_data.file_data は bytea。ファイルの実体をそのまま表に持つ。サイズの上限は、旧実装の設定を確認すること。要確認。
CREATE SCHEMA IF NOT EXISTS pxr_binary_manage;

-- FileUploadDataEntity.ts
CREATE TABLE IF NOT EXISTS pxr_binary_manage.file_upload_data (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_upload_manage_id  varchar(255) NOT NULL,
    seq_no                 bigint NOT NULL DEFAULT 0,
    file_data              bytea NOT NULL,
    created_by             varchar(255) NOT NULL,
    created_at             timestamp without time zone NOT NULL DEFAULT now(),
    updated_by             varchar(255) NOT NULL,
    updated_at             timestamp without time zone NOT NULL DEFAULT now()
);

-- FileUploadManageEntity.ts
CREATE TABLE IF NOT EXISTS pxr_binary_manage.file_upload_manage (
    id           varchar(255) PRIMARY KEY,
    file_name    varchar(255) NOT NULL,
    status       smallint NOT NULL DEFAULT 0,
    chunk_count  bigint NOT NULL DEFAULT 0,
    is_disabled  boolean NOT NULL DEFAULT false,
    created_by   varchar(255) NOT NULL,
    created_at   timestamp without time zone NOT NULL DEFAULT now(),
    updated_by   varchar(255) NOT NULL,
    updated_at   timestamp without time zone NOT NULL DEFAULT now()
);
