-- 移植：旧 pxr-ctoken-ledger-service の各エンティティ（src/repositories/postgres/*Entity.ts）から組み立てた。
-- 旧実装は synchronize: false で、テーブルの DDL をリポジトリに持たないため、エンティティの定義から起こした。
-- 旧 MIT ライセンス（Copyright 2022 NEC Corporation）の表示は NOTICE を参照。
-- 旧 ormconfig の database は pxr_pod、schema は pxr_ctoken_ledger。DB の作成は含まない。
-- TypeORM の既定（nullable 指定なし = NOT NULL）に従う。nullable: true の列はない。
-- 列名が数字で始まるものは、PostgreSQL の識別子として二重引用符で囲んだ。
--
-- 注記（エンティティの定義と、DDL の対応）
-- - 各エンティティの OneToMany / ManyToOne は、外部キー制約として起こしていない（他の単位と同じ扱い）。
-- - ctoken.ctoken_create_at、ctoken_history.ctoken_create_at などの onUpdate: 'now()' は TypeORM の更新時の指定のため、DDL の DEFAULT には含めていない。
-- - event_start_at、event_end_at、ワークフロー・アプリケーション識別子の列は、エンティティに nullable の指定がないため NOT NULL。要確認。

CREATE SCHEMA IF NOT EXISTS pxr_ctoken_ledger;

CREATE TABLE IF NOT EXISTS pxr_ctoken_ledger.ctoken (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pxr_id              varchar(255) NOT NULL,
    ctoken              varchar(255) NOT NULL,
    ctoken_create_at    timestamp without time zone NOT NULL,
    is_disabled         boolean NOT NULL DEFAULT false,
    created_by          varchar(255) NOT NULL,
    created_at          timestamp without time zone NOT NULL DEFAULT now(),
    updated_by          varchar(255) NOT NULL,
    updated_at          timestamp without time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pxr_ctoken_ledger.ctoken_history (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ctoken_id           bigint NOT NULL,
    ctoken              varchar(255) NOT NULL,
    ctoken_create_at    timestamp without time zone NOT NULL,
    is_disabled         boolean NOT NULL DEFAULT false,
    created_by          varchar(255) NOT NULL,
    created_at          timestamp without time zone NOT NULL DEFAULT now(),
    updated_by          varchar(255) NOT NULL,
    updated_at          timestamp without time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pxr_ctoken_ledger.cmatrix (
    id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ctoken_id                   bigint NOT NULL,
    actor_catalog_code          bigint NOT NULL,
    actor_catalog_version       bigint NOT NULL,
    "1_1"                       varchar(255) NOT NULL,
    cmatrix_hash                varchar(255) NOT NULL,
    cmatrix_hash_create_at      timestamp without time zone NOT NULL,
    is_disabled                 boolean NOT NULL DEFAULT false,
    created_by                  varchar(255) NOT NULL,
    created_at                  timestamp without time zone NOT NULL DEFAULT now(),
    updated_by                  varchar(255) NOT NULL,
    updated_at                  timestamp without time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pxr_ctoken_ledger.row_hash (
    id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cmatrix_id                  bigint NOT NULL,
    "3_1_1"                     varchar(255) NOT NULL,
    "3_1_2_1"                   bigint NOT NULL,
    "3_1_2_2"                   bigint NOT NULL,
    "3_2_1"                     timestamp without time zone NOT NULL,
    "3_2_2"                     timestamp without time zone NOT NULL,
    "3_5_1_1"                   bigint NOT NULL,
    "3_5_1_2"                   bigint NOT NULL,
    "3_5_2_1"                   bigint NOT NULL,
    "3_5_2_2"                   bigint NOT NULL,
    "3_5_5_1"                   bigint NOT NULL,
    "3_5_5_2"                   bigint NOT NULL,
    "4_1_1"                     varchar(255) NOT NULL,
    "4_1_2_1"                   bigint NOT NULL,
    "4_1_2_2"                   bigint NOT NULL,
    "4_4_1_1"                   bigint NOT NULL,
    "4_4_1_2"                   bigint NOT NULL,
    "4_4_2_1"                   bigint NOT NULL,
    "4_4_2_2"                   bigint NOT NULL,
    "4_4_5_1"                   bigint NOT NULL,
    "4_4_5_2"                   bigint NOT NULL,
    row_hash                    varchar(255) NOT NULL,
    row_hash_create_at          timestamp without time zone NOT NULL,
    is_disabled                 boolean NOT NULL DEFAULT false,
    created_by                  varchar(255) NOT NULL,
    created_at                  timestamp without time zone NOT NULL DEFAULT now(),
    updated_by                  varchar(255) NOT NULL,
    updated_at                  timestamp without time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pxr_ctoken_ledger.document (
    id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    row_hash_id                 bigint NOT NULL,
    "_1_1"                      varchar(255) NOT NULL,
    "_1_2_1"                    bigint NOT NULL,
    "_1_2_2"                    bigint NOT NULL,
    "_2_1"                      timestamp without time zone NOT NULL,
    "_3_1_1"                    bigint NOT NULL,
    "_3_1_2"                    bigint NOT NULL,
    "_3_2_1"                    bigint NOT NULL,
    "_3_2_2"                    bigint NOT NULL,
    "_3_5_1"                    bigint NOT NULL,
    "_3_5_2"                    bigint NOT NULL,
    is_disabled                 boolean NOT NULL DEFAULT false,
    created_by                  varchar(255) NOT NULL,
    created_at                  timestamp without time zone NOT NULL DEFAULT now(),
    updated_by                  varchar(255) NOT NULL,
    updated_at                  timestamp without time zone NOT NULL DEFAULT now()
);
