-- 移植：旧 pxr-book-operate-service の各エンティティ（src/repositories/postgres/*.ts）から組み立てた。
-- 旧実装は synchronize: false で、テーブルの DDL をリポジトリに持たないため、エンティティの定義から起こした。
-- 旧 MIT ライセンス（Copyright 2022 NEC Corporation）の表示は NOTICE を参照。
-- 旧 ormconfig の database は pxr_pod、schema は pxr_book_operate。DB の作成は含まない。
-- TypeORM の既定（nullable 指定なし = NOT NULL）に従う。例外は下の注記。
--
-- 注記（エンティティの定義と、DDL の対応）
-- - 外部キー制約は起こしていない（他の単位と同じ扱い）。
-- - nullable: true と指定された列は NULL を許す（3 列）。
-- - エンティティの default: false が列の型（smallint、bigint）に合わない 3 列（share_access_log.data_type など）は、DEFAULT を付けなかった。要確認。
CREATE SCHEMA IF NOT EXISTS pxr_book_operate;

-- BinaryFile.ts
CREATE TABLE IF NOT EXISTS pxr_book_operate.binary_file (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thing_id     bigint NOT NULL,
    file_path    varchar(255) NOT NULL,
    mime_type    varchar(255) NOT NULL,
    file_size    bigint NOT NULL,
    file_hash    varchar(255) NOT NULL,
    is_disabled  boolean NOT NULL DEFAULT false,
    created_by   varchar(255) NOT NULL,
    created_at   timestamp without time zone NOT NULL DEFAULT now(),
    updated_by   varchar(255) NOT NULL,
    updated_at   timestamp without time zone NOT NULL DEFAULT now()
);

-- Cmatrix2n.ts
CREATE TABLE IF NOT EXISTS pxr_book_operate.cmatrix_2_n (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    _1_1         varchar(255) NOT NULL,
    _1_2_1       bigint NOT NULL,
    _1_2_2       bigint NOT NULL,
    _2_1         timestamp without time zone NOT NULL,
    _3_1_1       bigint NOT NULL,
    _3_1_2       bigint NOT NULL,
    _3_2_1       bigint NOT NULL,
    _3_2_2       bigint NOT NULL,
    _3_3_1       bigint NOT NULL,
    _3_3_2       bigint NOT NULL,
    _3_4         varchar(255) NOT NULL,
    _3_5_1       bigint NOT NULL,
    _3_5_2       bigint NOT NULL,
    is_disabled  boolean NOT NULL DEFAULT false,
    created_by   varchar(255) NOT NULL,
    created_at   timestamp without time zone NOT NULL DEFAULT now(),
    updated_by   varchar(255) NOT NULL,
    updated_at   timestamp without time zone NOT NULL DEFAULT now()
);

-- Cmatrix2nRelation.ts
CREATE TABLE IF NOT EXISTS pxr_book_operate.cmatrix_2_n_relation (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    n                 bigint NOT NULL,
    cmatrix_event_id  bigint NOT NULL,
    cmatrix_2n_id     bigint NOT NULL,
    is_disabled       boolean NOT NULL DEFAULT false,
    created_by        varchar(255) NOT NULL,
    created_at        timestamp without time zone NOT NULL DEFAULT now(),
    updated_by        varchar(255) NOT NULL,
    updated_at        timestamp without time zone NOT NULL DEFAULT now()
);

-- CmatrixEvent.ts
CREATE TABLE IF NOT EXISTS pxr_book_operate.cmatrix_event (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "1_1"        varchar(255) NOT NULL,
    "1_2"        timestamp without time zone NOT NULL,
    "1_3"        bigint NOT NULL,
    "3_1_1"      varchar(255) NOT NULL,
    "3_1_2_1"    bigint NOT NULL,
    "3_1_2_2"    bigint NOT NULL,
    "3_2_1"      timestamp without time zone NOT NULL,
    "3_2_2"      timestamp without time zone NOT NULL,
    "3_3_1"      varchar(255) NOT NULL,
    "3_5_1_1"    bigint NOT NULL,
    "3_5_1_2"    bigint NOT NULL,
    "3_5_2_1"    bigint NOT NULL,
    "3_5_2_2"    bigint NOT NULL,
    "3_5_3_1"    bigint NOT NULL,
    "3_5_3_2"    bigint NOT NULL,
    "3_5_4"      varchar(255) NOT NULL,
    "3_5_5_1"    bigint NOT NULL,
    "3_5_5_2"    bigint NOT NULL,
    is_disabled  boolean NOT NULL DEFAULT false,
    created_by   varchar(255) NOT NULL,
    created_at   timestamp without time zone NOT NULL DEFAULT now(),
    updated_by   varchar(255) NOT NULL,
    updated_at   timestamp without time zone NOT NULL DEFAULT now()
);

-- CmatrixFloatingColumn.ts
CREATE TABLE IF NOT EXISTS pxr_book_operate.cmatrix_floating_column (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cmatrix_thing_id  bigint NOT NULL,
    index_key         varchar(255) NOT NULL,
    value             varchar(255),
    is_disabled       boolean NOT NULL DEFAULT false,
    created_by        varchar(255) NOT NULL,
    created_at        timestamp without time zone NOT NULL DEFAULT now(),
    updated_by        varchar(255) NOT NULL,
    updated_at        timestamp without time zone NOT NULL DEFAULT now()
);

-- CmatrixThing.ts
CREATE TABLE IF NOT EXISTS pxr_book_operate.cmatrix_thing (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cmatrix_event_id    bigint NOT NULL,
    "4_1_1"             varchar(255) NOT NULL,
    "4_1_2_1"           bigint NOT NULL,
    "4_1_2_2"           bigint NOT NULL,
    "4_4_1_1"           bigint NOT NULL,
    "4_4_1_2"           bigint NOT NULL,
    "4_4_2_1"           bigint NOT NULL,
    "4_4_2_2"           bigint NOT NULL,
    "4_4_3_1"           bigint NOT NULL,
    "4_4_3_2"           bigint NOT NULL,
    "4_4_4"             varchar(255) NOT NULL,
    "4_4_5_1"           bigint NOT NULL,
    "4_4_5_2"           bigint NOT NULL,
    row_hash            varchar(255) NOT NULL,
    row_hash_create_at  timestamp without time zone NOT NULL,
    is_disabled         boolean NOT NULL DEFAULT false,
    created_by          varchar(255) NOT NULL,
    created_at          timestamp without time zone NOT NULL DEFAULT now(),
    updated_by          varchar(255) NOT NULL,
    updated_at          timestamp without time zone NOT NULL DEFAULT now()
);

-- CollectionRequest.ts
CREATE TABLE IF NOT EXISTS pxr_book_operate.collection_request (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status              smallint NOT NULL DEFAULT 0,
    pcd_code            varchar(255) NOT NULL,
    actor_code          bigint NOT NULL,
    block_code          bigint NOT NULL,
    supply_proposal_id  bigint NOT NULL,
    contract_id         bigint NOT NULL,
    is_disabled         boolean NOT NULL DEFAULT false,
    created_by          varchar(255) NOT NULL,
    created_at          timestamp without time zone NOT NULL DEFAULT now(),
    updated_by          varchar(255) NOT NULL,
    updated_at          timestamp without time zone NOT NULL DEFAULT now()
);

-- CollectionRequestConsent.ts
CREATE TABLE IF NOT EXISTS pxr_book_operate.collection_request_consent (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_request_id  bigint NOT NULL,
    status                 smallint NOT NULL DEFAULT 0,
    user_id                varchar(255) NOT NULL,
    mask_id                varchar(255) NOT NULL,
    is_disabled            boolean NOT NULL DEFAULT false,
    created_by             varchar(255) NOT NULL,
    created_at             timestamp without time zone NOT NULL DEFAULT now(),
    updated_by             varchar(255) NOT NULL,
    updated_at             timestamp without time zone NOT NULL DEFAULT now()
);

-- CollectionRequestConsentDataAmount.ts
CREATE TABLE IF NOT EXISTS pxr_book_operate.collection_request_consent_data_amount (
    id                             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_request_consent_id  bigint NOT NULL,
    event_code                     bigint NOT NULL,
    event_version                  bigint NOT NULL,
    thing_code                     bigint NOT NULL,
    thing_version                  bigint NOT NULL,
    amount                         bigint NOT NULL,
    is_disabled                    boolean NOT NULL DEFAULT false,
    created_by                     varchar(255) NOT NULL,
    created_at                     timestamp without time zone NOT NULL DEFAULT now(),
    updated_by                     varchar(255) NOT NULL,
    updated_at                     timestamp without time zone NOT NULL DEFAULT now()
);

-- CollectionRequestDataType.ts
CREATE TABLE IF NOT EXISTS pxr_book_operate.collection_request_data_type (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_request_id  bigint NOT NULL,
    event_code             bigint NOT NULL,
    event_version          bigint NOT NULL,
    thing_code             bigint NOT NULL,
    thing_version          bigint NOT NULL,
    is_disabled            boolean NOT NULL DEFAULT false,
    created_by             varchar(255) NOT NULL,
    created_at             timestamp without time zone NOT NULL DEFAULT now(),
    updated_by             varchar(255) NOT NULL,
    updated_at             timestamp without time zone NOT NULL DEFAULT now()
);

-- Document.ts
CREATE TABLE IF NOT EXISTS pxr_book_operate.document (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    my_condition_book_id  bigint NOT NULL,
    source_id             varchar(255) NOT NULL,
    doc_identifier        varchar(255) NOT NULL,
    doc_catalog_code      bigint NOT NULL,
    doc_catalog_version   bigint NOT NULL,
    doc_create_at         timestamp without time zone NOT NULL DEFAULT now(),
    doc_actor_code        bigint NOT NULL,
    doc_actor_version     bigint NOT NULL,
    wf_catalog_code       bigint NOT NULL,
    wf_catalog_version    bigint NOT NULL,
    wf_role_code          bigint NOT NULL,
    wf_role_version       bigint NOT NULL,
    wf_staff_identifier   varchar(255) NOT NULL,
    app_catalog_code      bigint NOT NULL,
    app_catalog_version   bigint NOT NULL,
    template              text NOT NULL,
    attributes            text NOT NULL,
    is_disabled           boolean NOT NULL DEFAULT false,
    created_by            varchar(255) NOT NULL,
    created_at            timestamp without time zone NOT NULL DEFAULT now(),
    updated_by            varchar(255) NOT NULL,
    updated_at            timestamp without time zone NOT NULL DEFAULT now()
);

-- DocumentEventSetRelation.ts
CREATE TABLE IF NOT EXISTS pxr_book_operate.document_event_set_relation (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id  bigint NOT NULL,
    title        varchar(255) NOT NULL,
    attributes   text NOT NULL,
    is_disabled  boolean NOT NULL DEFAULT false,
    created_by   varchar(255) NOT NULL,
    created_at   timestamp without time zone NOT NULL DEFAULT now(),
    updated_by   varchar(255) NOT NULL,
    updated_at   timestamp without time zone NOT NULL DEFAULT now()
);

-- Event.ts
CREATE TABLE IF NOT EXISTS pxr_book_operate.event (
    id                       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    my_condition_book_id     bigint NOT NULL,
    source_id                varchar(255) NOT NULL,
    event_identifier         varchar(255) NOT NULL,
    event_catalog_code       bigint NOT NULL,
    event_catalog_version    bigint NOT NULL,
    event_start_at           timestamp without time zone NOT NULL DEFAULT now(),
    event_end_at             timestamp without time zone NOT NULL DEFAULT now(),
    event_outbreak_position  bigint NOT NULL,
    event_actor_code         bigint NOT NULL,
    event_actor_version      bigint NOT NULL,
    wf_catalog_code          bigint NOT NULL,
    wf_catalog_version       bigint NOT NULL,
    wf_role_code             bigint NOT NULL,
    wf_role_version          bigint NOT NULL,
    wf_staff_identifier      varchar(255) NOT NULL,
    app_catalog_code         bigint NOT NULL,
    app_catalog_version      bigint NOT NULL,
    template                 text NOT NULL,
    attributes               text NOT NULL,
    is_disabled              boolean NOT NULL DEFAULT false,
    created_by               varchar(255) NOT NULL,
    created_at               timestamp without time zone NOT NULL DEFAULT now(),
    updated_by               varchar(255) NOT NULL,
    updated_at               timestamp without time zone NOT NULL DEFAULT now()
);

-- EventSetEventRelation.ts
CREATE TABLE IF NOT EXISTS pxr_book_operate.event_set_event_relation (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_set_id          bigint NOT NULL,
    event_id              bigint NOT NULL,
    source_id_at_created  varchar(255) NOT NULL,
    attributes            text NOT NULL,
    is_disabled           boolean NOT NULL DEFAULT false,
    created_by            varchar(255) NOT NULL,
    created_at            timestamp without time zone NOT NULL DEFAULT now(),
    updated_by            varchar(255) NOT NULL,
    updated_at            timestamp without time zone NOT NULL DEFAULT now()
);

-- MyConditionBook.ts
CREATE TABLE IF NOT EXISTS pxr_book_operate.my_condition_book (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 varchar(255) NOT NULL,
    actor_catalog_code      bigint NOT NULL,
    actor_catalog_version   bigint NOT NULL,
    region_catalog_code     bigint NOT NULL,
    region_catalog_version  bigint NOT NULL,
    app_catalog_code        bigint NOT NULL,
    app_catalog_version     bigint NOT NULL,
    wf_catalog_code         bigint NOT NULL,
    wf_catalog_version      bigint NOT NULL,
    open_start_at           timestamp without time zone NOT NULL DEFAULT now(),
    identify_code           varchar(255) NOT NULL,
    attributes              text NOT NULL,
    is_disabled             boolean NOT NULL DEFAULT false,
    created_by              varchar(255) NOT NULL,
    created_at              timestamp without time zone NOT NULL DEFAULT now(),
    updated_by              varchar(255) NOT NULL,
    updated_at              timestamp without time zone NOT NULL DEFAULT now()
);

-- ShareAccessLog.ts
CREATE TABLE IF NOT EXISTS pxr_book_operate.shared_access_log (
    id                         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    my_condition_book_id       bigint NOT NULL,
    log_identifier             varchar(255) NOT NULL,
    user_name                  varchar(255) NOT NULL,
    data_type                  smallint NOT NULL,
    share_catalog_code         bigint NOT NULL,
    req_actor_catalog_code     bigint NOT NULL,
    req_actor_catalog_version  bigint NOT NULL,
    req_block_catalog_code     bigint NOT NULL,
    req_block_catalog_version  bigint NOT NULL,
    access_at                  timestamp without time zone NOT NULL DEFAULT now(),
    is_disabled                boolean NOT NULL DEFAULT false,
    created_by                 varchar(255) NOT NULL,
    created_at                 timestamp without time zone NOT NULL DEFAULT now(),
    updated_by                 varchar(255) NOT NULL,
    updated_at                 timestamp without time zone NOT NULL DEFAULT now()
);

-- ShareAccessLogDataType.ts
CREATE TABLE IF NOT EXISTS pxr_book_operate.shared_access_log_data_type (
    id                         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    share_access_log_id        bigint NOT NULL,
    data_type                  smallint NOT NULL,
    data_type_catalog_code     bigint NOT NULL,
    data_type_catalog_version  bigint NOT NULL,
    attributes                 text NOT NULL,
    is_disabled                boolean NOT NULL DEFAULT false,
    created_by                 varchar(255) NOT NULL,
    created_at                 timestamp without time zone NOT NULL DEFAULT now(),
    updated_by                 varchar(255) NOT NULL,
    updated_at                 timestamp without time zone NOT NULL DEFAULT now()
);

-- ShareStatus.ts
CREATE TABLE IF NOT EXISTS pxr_book_operate.share_status (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                varchar(255) NOT NULL,
    share_trigger_code     bigint NOT NULL,
    share_trigger_version  bigint NOT NULL,
    share_code             bigint NOT NULL,
    share_version          bigint NOT NULL,
    end_method             bigint NOT NULL,
    start_datetime         timestamp without time zone DEFAULT now(),
    end_datetime           timestamp without time zone DEFAULT now(),
    status                 smallint NOT NULL,
    is_disabled            boolean NOT NULL DEFAULT false,
    created_by             varchar(255) NOT NULL,
    created_at             timestamp without time zone NOT NULL DEFAULT now(),
    updated_by             varchar(255) NOT NULL,
    updated_at             timestamp without time zone NOT NULL DEFAULT now()
);

-- ShareTriggerWaiting.ts
CREATE TABLE IF NOT EXISTS pxr_book_operate.share_trigger_waiting (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    share_status_id        bigint NOT NULL,
    user_id                varchar(255) NOT NULL,
    share_trigger_code     bigint NOT NULL,
    share_trigger_version  bigint NOT NULL,
    share_code             bigint NOT NULL,
    share_version          bigint NOT NULL,
    source_actor_code      bigint NOT NULL,
    source_actor_version   bigint NOT NULL,
    source_app_code        bigint NOT NULL,
    source_app_version     bigint NOT NULL,
    source_wf_code         bigint NOT NULL,
    source_wf_version      bigint NOT NULL,
    dest_actor_code        bigint NOT NULL,
    dest_actor_version     bigint NOT NULL,
    dest_app_code          bigint NOT NULL,
    dest_app_version       bigint NOT NULL,
    dest_wf_code           bigint NOT NULL,
    dest_wf_version        bigint NOT NULL,
    process_type           smallint NOT NULL,
    end_of_waiting_at      timestamp without time zone NOT NULL,
    identifier             varchar(255) NOT NULL,
    is_disabled            boolean NOT NULL DEFAULT false,
    created_by             varchar(255) NOT NULL,
    created_at             timestamp without time zone NOT NULL DEFAULT now(),
    updated_by             varchar(255) NOT NULL,
    updated_at             timestamp without time zone NOT NULL DEFAULT now()
);

-- Thing.ts
CREATE TABLE IF NOT EXISTS pxr_book_operate.thing (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id               bigint NOT NULL,
    source_id              varchar(255) NOT NULL,
    thing_identifier       varchar(255) NOT NULL,
    thing_catalog_code     bigint NOT NULL,
    thing_catalog_version  bigint NOT NULL,
    thing_actor_code       bigint NOT NULL,
    thing_actor_version    bigint NOT NULL,
    wf_catalog_code        bigint NOT NULL,
    wf_catalog_version     bigint NOT NULL,
    wf_role_code           bigint NOT NULL,
    wf_role_version        bigint NOT NULL,
    wf_staff_identifier    varchar(255) NOT NULL,
    app_catalog_code       bigint NOT NULL,
    app_catalog_version    bigint NOT NULL,
    template               text NOT NULL,
    attributes             text NOT NULL,
    is_disabled            boolean NOT NULL DEFAULT false,
    created_by             varchar(255) NOT NULL,
    created_at             timestamp without time zone NOT NULL DEFAULT now(),
    updated_by             varchar(255) NOT NULL,
    updated_at             timestamp without time zone NOT NULL DEFAULT now()
);
