-- 移植：旧 pxr-catalog-update-service の各エンティティ（src/repositories/postgres/*.ts、15 個）から組み立てた。
-- 旧実装は synchronize: false で、テーブルの DDL をリポジトリに持たないため、エンティティの定義から起こした。
-- 旧 MIT ライセンス（Copyright 2022 NEC Corporation）の表示は NOTICE を参照。
-- 旧 ormconfig の database は pxr_pod、schema は pxr_catalog_update。DB の作成は含まない。
-- TypeORM の既定（nullable 指定なし = NOT NULL）に従う。nullable: true の列はない。
--
-- 注記（エンティティの定義と、DDL の対応）
-- - 外部キー制約は起こしていない（他の単位と同じ扱い）。
-- - エンティティの default: false が timestamp の列（application_at）に付いている 2 列は、型に合わないため DEFAULT を付けていない。要確認。
CREATE SCHEMA IF NOT EXISTS pxr_catalog_update;

-- ActorApprovalManage.ts
CREATE TABLE IF NOT EXISTS pxr_catalog_update.actor_approval_manage (
    id                       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_manage_id          bigint NOT NULL,
    auth_code                varchar NOT NULL,
    status                   smallint NOT NULL DEFAULT 0,
    comment                  text NOT NULL,
    migration_actor_code     bigint NOT NULL,
    migration_actor_version  bigint NOT NULL,
    migration_comment        text NOT NULL,
    migragtion_approver      varchar(255) NOT NULL,
    migration_approval_at    timestamp without time zone NOT NULL,
    approval_actor_code      bigint NOT NULL,
    approval_actor_version   bigint NOT NULL,
    approver                 varchar(255) NOT NULL,
    approval_at              timestamp without time zone NOT NULL,
    is_disabled              boolean NOT NULL DEFAULT false,
    created_by               varchar(255) NOT NULL,
    created_at               timestamp without time zone NOT NULL DEFAULT now(),
    updated_by               varchar(255) NOT NULL,
    updated_at               timestamp without time zone NOT NULL DEFAULT now()
);

-- ActorManage.ts
CREATE TABLE IF NOT EXISTS pxr_catalog_update.actor_manage (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    caller_actor_code     bigint NOT NULL,
    caller_actor_version  bigint NOT NULL,
    caller_block_code     bigint NOT NULL,
    caller_block_version  bigint NOT NULL,
    template              text NOT NULL,
    approval_expire_at    timestamp without time zone NOT NULL,
    type                  smallint NOT NULL,
    applicant_date        timestamp without time zone NOT NULL,
    is_draft              boolean NOT NULL DEFAULT false,
    attributes            text NOT NULL,
    is_disabled           boolean NOT NULL DEFAULT false,
    created_by            varchar(255) NOT NULL,
    created_at            timestamp without time zone NOT NULL DEFAULT now(),
    updated_by            varchar(255) NOT NULL,
    updated_at            timestamp without time zone NOT NULL DEFAULT now()
);

-- AllianceApprovalManage.ts
CREATE TABLE IF NOT EXISTS pxr_catalog_update.alliance_approval_manage (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alliance_manage_id      bigint NOT NULL,
    auth_code               varchar(255) NOT NULL,
    status                  smallint NOT NULL DEFAULT 0,
    comment                 text NOT NULL,
    approval_actor_code     bigint NOT NULL,
    approval_actor_version  bigint NOT NULL,
    approver                varchar(255) NOT NULL,
    approval_at             timestamp without time zone NOT NULL,
    is_disabled             boolean NOT NULL DEFAULT false,
    created_by              varchar(255) NOT NULL,
    created_at              timestamp without time zone NOT NULL DEFAULT now(),
    updated_by              varchar(255) NOT NULL,
    updated_at              timestamp without time zone NOT NULL DEFAULT now()
);

-- AllianceManage.ts
CREATE TABLE IF NOT EXISTS pxr_catalog_update.alliance_manage (
    id                         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alliance_trader_code       bigint NOT NULL,
    alliance_trader_version    bigint NOT NULL,
    alliance_consumer_code     bigint NOT NULL,
    alliance_consumer_version  bigint NOT NULL,
    alliance_region_code       bigint NOT NULL,
    alliance_region_version    bigint NOT NULL,
    applicant_actor_code       bigint NOT NULL,
    applicant_actor_version    bigint NOT NULL,
    approval_expire_at         timestamp without time zone NOT NULL,
    type                       smallint NOT NULL,
    applicant_date             timestamp without time zone NOT NULL,
    is_draft                   boolean NOT NULL DEFAULT false,
    is_disabled                boolean NOT NULL DEFAULT false,
    created_by                 varchar(255) NOT NULL,
    created_at                 timestamp without time zone NOT NULL DEFAULT now(),
    updated_by                 varchar(255) NOT NULL,
    updated_at                 timestamp without time zone NOT NULL DEFAULT now()
);

-- AuditReportManage.ts
CREATE TABLE IF NOT EXISTS pxr_catalog_update.audit_report_manage (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_actor_code     bigint NOT NULL,
    target_actor_version  bigint NOT NULL,
    audit_actor_code      bigint NOT NULL,
    audit_actor_version   bigint NOT NULL,
    auditor               varchar(255) NOT NULL,
    report_template       text NOT NULL,
    report_created_at     timestamp without time zone NOT NULL,
    isDraft               boolean NOT NULL DEFAULT false,
    is_disabled           boolean NOT NULL DEFAULT false,
    created_by            varchar(255) NOT NULL,
    created_at            timestamp without time zone NOT NULL DEFAULT now(),
    updated_by            varchar(255) NOT NULL,
    updated_at            timestamp without time zone NOT NULL DEFAULT now()
);

-- DataOperationManage.ts
CREATE TABLE IF NOT EXISTS pxr_catalog_update.data_operation_manage (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template                text NOT NULL,
    application_actor_code  bigint NOT NULL,
    application_block_code  bigint NOT NULL,
    application_at          timestamp without time zone NOT NULL,
    is_draft                boolean NOT NULL DEFAULT false,
    is_disabled             boolean NOT NULL DEFAULT false,
    created_by              varchar(255) NOT NULL,
    created_at              timestamp without time zone NOT NULL DEFAULT now(),
    updated_by              varchar(255) NOT NULL,
    updated_at              timestamp without time zone NOT NULL DEFAULT now()
);

-- JoinApprovalManage.ts
CREATE TABLE IF NOT EXISTS pxr_catalog_update.join_approval_manage (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    join_manage_id          bigint NOT NULL,
    auth_code               varchar(255) NOT NULL,
    status                  smallint NOT NULL DEFAULT 0,
    comment                 text NOT NULL,
    approval_actor_code     bigint NOT NULL,
    approval_actor_version  bigint NOT NULL,
    approver                varchar(255) NOT NULL,
    approval_at             timestamp without time zone NOT NULL,
    is_disabled             boolean NOT NULL DEFAULT false,
    created_by              varchar(255) NOT NULL,
    created_at              timestamp without time zone NOT NULL DEFAULT now(),
    updated_by              varchar(255) NOT NULL,
    updated_at              timestamp without time zone NOT NULL DEFAULT now()
);

-- JoinManage.ts
CREATE TABLE IF NOT EXISTS pxr_catalog_update.join_manage (
    id                       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    join_actor_code          bigint NOT NULL,
    join_actor_version       bigint NOT NULL,
    join_region_code         bigint NOT NULL,
    join_region_version      bigint NOT NULL,
    applicant_actor_code     bigint NOT NULL,
    applicant_actor_version  bigint NOT NULL,
    approval_expire_at       timestamp without time zone NOT NULL,
    type                     smallint NOT NULL,
    applicant_date           timestamp without time zone NOT NULL,
    is_draft                 boolean NOT NULL DEFAULT false,
    is_disabled              boolean NOT NULL DEFAULT false,
    created_by               varchar(255) NOT NULL,
    created_at               timestamp without time zone NOT NULL DEFAULT now(),
    updated_by               varchar(255) NOT NULL,
    updated_at               timestamp without time zone NOT NULL DEFAULT now()
);

-- JoinServiceManage.ts
CREATE TABLE IF NOT EXISTS pxr_catalog_update.join_service_manage (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    join_manage_id   bigint NOT NULL,
    type             smallint NOT NULL,
    service_code     bigint NOT NULL,
    service_version  bigint NOT NULL,
    is_disabled      boolean NOT NULL DEFAULT false,
    created_by       varchar(255) NOT NULL,
    created_at       timestamp without time zone NOT NULL DEFAULT now(),
    updated_by       varchar(255) NOT NULL,
    updated_at       timestamp without time zone NOT NULL DEFAULT now()
);

-- PlatformTermsOfUseManage.ts
CREATE TABLE IF NOT EXISTS pxr_catalog_update.platform_terms_of_use_manage (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    terms_of_use_code       bigint NOT NULL,
    terms_of_use_version    bigint NOT NULL,
    template                text NOT NULL,
    application_actor_code  bigint NOT NULL,
    application_block_code  bigint NOT NULL,
    application_at          timestamp without time zone NOT NULL,
    is_disabled             boolean NOT NULL DEFAULT false,
    created_by              varchar(255) NOT NULL,
    created_at              timestamp without time zone NOT NULL DEFAULT now(),
    updated_by              varchar(255) NOT NULL,
    updated_at              timestamp without time zone NOT NULL DEFAULT now()
);

-- RegionApprovalManage.ts
CREATE TABLE IF NOT EXISTS pxr_catalog_update.region_approval_manage (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_manage_id        bigint NOT NULL,
    auth_code               varchar(255) NOT NULL,
    status                  bigint NOT NULL DEFAULT 0,
    comment                 text NOT NULL,
    approval_actor_code     bigint NOT NULL,
    approval_actor_version  bigint NOT NULL,
    approver                varchar(255) NOT NULL,
    approval_at             timestamp without time zone NOT NULL,
    is_disabled             boolean NOT NULL DEFAULT false,
    created_by              varchar(255) NOT NULL,
    created_at              timestamp without time zone NOT NULL DEFAULT now(),
    updated_by              varchar(255) NOT NULL,
    updated_at              timestamp without time zone NOT NULL DEFAULT now()
);

-- RegionManage.ts
CREATE TABLE IF NOT EXISTS pxr_catalog_update.region_manage (
    id                       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_code              bigint NOT NULL,
    region_version           bigint NOT NULL,
    caller_block_code        bigint NOT NULL,
    caller_block_version     bigint NOT NULL,
    applicant_actor_code     bigint NOT NULL,
    applicant_actor_version  bigint NOT NULL,
    approval_actor_code      bigint NOT NULL,
    approval_actor_version   bigint NOT NULL,
    template                 text NOT NULL,
    approval_expire_at       timestamp without time zone NOT NULL,
    type                     bigint NOT NULL,
    is_draft                 boolean NOT NULL DEFAULT false,
    is_disabled              boolean NOT NULL DEFAULT false,
    created_by               bigint NOT NULL,
    created_at               timestamp without time zone NOT NULL DEFAULT now(),
    updated_by               bigint NOT NULL,
    updated_at               timestamp without time zone NOT NULL DEFAULT now()
);

-- RegionStatusApprovalManage.ts
CREATE TABLE IF NOT EXISTS pxr_catalog_update.region_status_approval_manage (
    id                       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_status_manage_id  bigint NOT NULL,
    auth_code                varchar(255) NOT NULL,
    status                   bigint NOT NULL DEFAULT 0,
    comment                  text NOT NULL,
    approval_actor_code      bigint NOT NULL,
    approval_actor_version   bigint NOT NULL,
    approver                 varchar(255) NOT NULL,
    approval_at              timestamp without time zone NOT NULL,
    is_disabled              boolean NOT NULL DEFAULT false,
    created_by               varchar(255) NOT NULL,
    created_at               timestamp without time zone NOT NULL DEFAULT now(),
    updated_by               varchar(255) NOT NULL,
    updated_at               timestamp without time zone NOT NULL DEFAULT now()
);

-- RegionStatusManage.ts
CREATE TABLE IF NOT EXISTS pxr_catalog_update.region_status_manage (
    id                       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_code              bigint NOT NULL,
    region_version           bigint NOT NULL,
    caller_block_code        bigint NOT NULL,
    caller_block_version     bigint NOT NULL,
    applicant_actor_code     bigint NOT NULL,
    applicant_actor_version  bigint NOT NULL,
    approval_actor_code      bigint NOT NULL,
    approval_actor_version   bigint NOT NULL,
    approval_expire_at       timestamp without time zone NOT NULL,
    type                     bigint NOT NULL,
    end_date                 timestamp without time zone NOT NULL,
    request_comment          text NOT NULL,
    is_disabled              boolean NOT NULL DEFAULT false,
    created_by               bigint NOT NULL,
    created_at               timestamp without time zone NOT NULL DEFAULT now(),
    updated_by               bigint NOT NULL,
    updated_at               timestamp without time zone NOT NULL DEFAULT now()
);

-- RegionTermsOfUseManage.ts
CREATE TABLE IF NOT EXISTS pxr_catalog_update.region_terms_of_use_manage (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    terms_of_use_code       bigint NOT NULL,
    terms_of_use_version    bigint NOT NULL,
    template                text NOT NULL,
    application_actor_code  bigint NOT NULL,
    application_block_code  bigint NOT NULL,
    application_at          timestamp without time zone NOT NULL,
    is_disabled             boolean NOT NULL DEFAULT false,
    created_by              varchar(255) NOT NULL,
    created_at              timestamp without time zone NOT NULL DEFAULT now(),
    updated_by              varchar(255) NOT NULL,
    updated_at              timestamp without time zone NOT NULL DEFAULT now()
);
