-- 移植：旧 pxr-local-ctoken-service の各エンティティ（src/repositories/postgres/*.ts）から組み立てた。
-- 旧実装は synchronize: false で、テーブルの DDL をリポジトリに持たないため、エンティティの定義から起こした。
-- 旧 MIT ライセンス（Copyright 2022 NEC Corporation）の表示は NOTICE を参照。
-- 旧 ormconfig の database は pxr_pod、schema は pxr_local_ctoken。DB の作成は含まない。
-- TypeORM の既定（nullable 指定なし = NOT NULL）に従う。nullable: true の列はない。
-- 列名が数字で始まるものは、PostgreSQL の識別子として二重引用符で囲んだ。
--
-- 注記（エンティティの定義と、DDL の対応）
-- - 外部キー制約は起こしていない（他の単位と同じ扱い）。
-- - 列名の _1_1 などは、そのまま使った（先頭がアンダースコアのため引用不要）。
CREATE SCHEMA IF NOT EXISTS pxr_local_ctoken;

-- DocumentEntity.ts
CREATE TABLE IF NOT EXISTS pxr_local_ctoken.document (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    row_hash_id  bigint NOT NULL,
    _1_1         varchar(255) NOT NULL,
    _1_2_1       bigint NOT NULL,
    _1_2_2       bigint NOT NULL,
    _2_1         timestamp without time zone NOT NULL,
    _3_1_1       bigint NOT NULL,
    _3_1_2       bigint NOT NULL,
    _3_2_1       bigint NOT NULL,
    _3_2_2       bigint NOT NULL,
    _3_5_1       bigint NOT NULL,
    _3_5_2       bigint NOT NULL,
    is_disabled  boolean NOT NULL DEFAULT false,
    created_by   varchar(255) NOT NULL,
    created_at   timestamp without time zone NOT NULL DEFAULT now(),
    updated_by   varchar(255) NOT NULL,
    updated_at   timestamp without time zone NOT NULL DEFAULT now()
);

-- RowHashEntity.ts
CREATE TABLE IF NOT EXISTS pxr_local_ctoken.row_hash (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type                smallint NOT NULL,
    status              smallint NOT NULL,
    "1_1"               varchar(255) NOT NULL,
    "3_1_1"             varchar(255) NOT NULL,
    "3_1_2_1"           bigint NOT NULL,
    "3_1_2_2"           bigint NOT NULL,
    "3_2_1"             timestamp without time zone NOT NULL,
    "3_2_2"             timestamp without time zone NOT NULL,
    "3_5_1_1"           bigint NOT NULL,
    "3_5_1_2"           bigint NOT NULL,
    "3_5_2_1"           bigint NOT NULL,
    "3_5_2_2"           bigint NOT NULL,
    "3_5_5_1"           bigint NOT NULL,
    "3_5_5_2"           bigint NOT NULL,
    "4_1_1"             varchar(255) NOT NULL,
    "4_1_2_1"           bigint NOT NULL,
    "4_1_2_2"           bigint NOT NULL,
    "4_4_1_1"           bigint NOT NULL,
    "4_4_1_2"           bigint NOT NULL,
    "4_4_2_1"           bigint NOT NULL,
    "4_4_2_2"           bigint NOT NULL,
    "4_4_5_1"           bigint NOT NULL,
    "4_4_5_2"           bigint NOT NULL,
    row_hash            varchar(255) NOT NULL,
    row_hash_create_at  timestamp without time zone NOT NULL,
    is_disabled         boolean NOT NULL DEFAULT false,
    created_by          varchar(255) NOT NULL,
    created_at          timestamp without time zone NOT NULL DEFAULT now(),
    updated_by          varchar(255) NOT NULL,
    updated_at          timestamp without time zone NOT NULL DEFAULT now()
);
