-- 移植：旧 pxr-certificate-manage-service の TypeORM エンティティ（src/repositories/postgres/CertificateManage.ts）から組み立てた。
-- 旧実装は synchronize: false で、テーブルの DDL をリポジトリに持たないため、エンティティの定義から起こした。
-- 旧 MIT ライセンス（Copyright 2022 NEC Corporation）の表示は NOTICE を参照。
-- 旧 ormconfig の database は pxr_pod、schema は pxr_certificate_manage。DB の作成は含まない。
-- TypeORM の既定（nullable 指定なし = NOT NULL）に従う。nullable: true の列はない。
--
-- 注記（エンティティの定義と、DDL の対応）
-- - 表の中身は pxr_certification_authority.certificate_manage（PR #53）と同じ。旧ormconfig の schema だけが違う。両方の DB に、それぞれ立てる想定。要確認。
-- - 外部キー制約は起こしていない（他の単位と同じ扱い）。

CREATE SCHEMA IF NOT EXISTS pxr_certificate_manage;

-- CertificateManage.ts
CREATE TABLE IF NOT EXISTS pxr_certificate_manage.certificate_manage (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cert_type           varchar(255) NOT NULL,
    subject             text NOT NULL,
    serial_no           varchar(255) NOT NULL,
    finger_print        varchar(255) NOT NULL,
    valid_period_start  timestamp without time zone NOT NULL,
    valid_period_end    timestamp without time zone NOT NULL,
    certificate         text NOT NULL,
    actor_code          bigint NOT NULL,
    actor_version       bigint NOT NULL,
    block_code          bigint NOT NULL,
    block_version       bigint NOT NULL,
    is_distributed      boolean NOT NULL DEFAULT false,
    is_disabled         boolean NOT NULL DEFAULT false,
    created_by          varchar(255) NOT NULL,
    created_at          timestamp without time zone NOT NULL DEFAULT now(),
    updated_by          varchar(255) NOT NULL,
    updated_at          timestamp without time zone NOT NULL DEFAULT now()
);
